#!/usr/bin/env python3
"""One-variable netlist control for sim/bias-core-startup/'s ``ok_bo_dip_mv`` (#185).

    python3 sim/bias-core-startup/control/run_ok_dip_decay.py

Composes one ngspice deck per (DUT netlist x corner) from
``ok_dip_decay.spice`` plus a verbatim copy of either the schematic export
(``design/netlist/bias_core.spice``) or the klt-extracted netlist
(``layout/postlayout/bias_core.spice``), and samples V(BIAS_OK) and V(VREF)
across a dead-rail window stretched from the parent testbench's 3 ms to
17 ms. It writes:

    decks/dip-<netlist>-<corner>.spice   the exact deck as run
    logs/dip-<netlist>-<corner>.log      raw ngspice output, verbatim
    dip_results.md                       the comparison table, from those logs

THE QUESTION. ``ok_bo_dip_mv`` samples V(BIAS_OK) once, at 35 ms -- 2 ms into
the parent deck's 3 ms dead-rail window -- against a +/-300 mV bound. On the
extracted netlist (record ``20260811-062115-5ff219c``) it reads 303.432 mV at
``ss_-40c_*`` where the schematic export reads 33.6 mV, and issue #185 has to
decide whether that is a held stale valid (the failure ``XMOKC`` exists to
prevent) or the same monotonic discharge with a longer time constant. One
sample cannot tell those apart; a curve can.

WHAT IS HELD FIXED. Everything except the DUT netlist: same fragment, same
process, same PDK, same corner sections, same solver tolerances (read from the
harness and from ``../testbench/tb.json``, not restated here). The two netlists
describe the same 70 devices -- per ``layout/postlayout/AUDIT.md`` the
extraction has no remaining ideal device -- so the delta is interconnect
parasitics and nothing else.

This is a diagnosis of record ``20260811-062115-5ff219c``, not a recorded PVT
result: a two-corner control is not evidence about the corner grid, so it
deliberately does NOT go through sim/run_corners.py and does NOT mint a record
under ../records/. See sim/README.md for the distinction.

Stdlib only, no virtualenv required.
"""

from __future__ import annotations

import json
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

CONTROL_DIR = Path(__file__).resolve().parent
EXPERIMENT_DIR = CONTROL_DIR.parent
REPO_ROOT = CONTROL_DIR.parents[2]

sys.path.insert(0, str(REPO_ROOT / "sim"))

from harness import HARNESS_VERSION, corners as corners_mod, runner  # noqa: E402
from harness.pdk import PdkNotFound, find_pdk  # noqa: E402

FRAGMENT = CONTROL_DIR / "ok_dip_decay.spice"
MANIFEST = EXPERIMENT_DIR / "testbench" / "tb.json"

#: the control's ONE variable
NETLISTS: list[tuple[str, Path, str]] = [
    ("schematic", REPO_ROOT / "design" / "netlist" / "bias_core.spice", "schematic export"),
    ("extracted", REPO_ROOT / "layout" / "postlayout" / "bias_core.spice", "klt-extracted"),
]

#: (corner, temp_c, label). ss/-40 C is the failing family in the parent
#: record; tt/27 C is the reference point that passes on both netlists.
POINTS: list[tuple[str, float, str]] = [
    ("ss", -40.0, "ss / -40 C  (the failing family)"),
    ("tt", 27.0, "tt / +27 C  (reference)"),
]

#: One supply: the parent record's own supply axis is degenerate here and its
#: ss/-40 C rows at 2.97 / 3.30 / 3.63 V are bit-identical.
VDD_V = 3.63

#: Sample times in ms. 33 ms is the instant the rail reaches 0 V; 35 ms is the
#: parent testbench's own `ok_bo_dip_mv` sample; 50 ms is the end of the
#: stretched window.
SAMPLE_MS: list[float] = [33.5, 34.0, 35.0, 36.0, 38.0, 40.0, 45.0, 50.0]

TSTOP_MS = 52.0
TSTEP_US = 20.0
DEAD_RAIL_START_MS = 33.0
PARENT_SAMPLE_MS = 35.0
PARENT_WINDOW_END_MS = 36.0


def _tag(ms: float) -> str:
    return f"{int(round(ms * 10))}"


def compose_deck(pdk, netlist: Path, corner_name: str, temp_c: float, options: list[str]) -> str:
    corner = corners_mod.CORNERS[corner_name]
    lines = [
        f"* ok_bo_dip decay control -- {netlist.name} @ {corner_name}/{temp_c} C",
        "* GENERATED by sim/bias-core-startup/control/run_ok_dip_decay.py, do not edit",
        f"* pdk={pdk.variant}@{pdk.version}  harness={HARNESS_VERSION}",
        "",
        ".param vdd_nom=3.3",
        f".param vdd_val={VDD_V!r}",
        f".param temp_c={temp_c!r}",
        "",
    ]
    lines += runner.deck_preamble(pdk, corner, temp_c, options)
    lines += ["", FRAGMENT.read_text().rstrip(), "", netlist.read_text().rstrip(), ""]
    lines += [".control", "set numdgt=10", "set noaskquit", f"  tran {TSTEP_US}u {TSTOP_MS}m"]
    for ms in SAMPLE_MS:
        lines.append(f"  meas tran ok{_tag(ms)} find v(bias_okb) at={ms}m")
        lines.append(f"  meas tran vr{_tag(ms)} find v(vrefb) at={ms}m")
    for ms in SAMPLE_MS:
        lines.append(f"  let m_ok{_tag(ms)} = ok{_tag(ms)}")
        lines.append(f"  let m_vr{_tag(ms)} = vr{_tag(ms)}")
    for ms in SAMPLE_MS:
        lines.append(f"  print m_ok{_tag(ms)}")
        lines.append(f"  print m_vr{_tag(ms)}")
    lines += [".endc", ".end", ""]
    return "\n".join(lines)


def run_one(job):
    pdk, options, deck_dir, log_dir, net_name, netlist, corner_name, temp_c = job
    name = f"dip-{net_name}-{corner_name}_{int(temp_c)}c"
    deck_path = deck_dir / f"{name}.spice"
    deck_path.write_text(compose_deck(pdk, netlist, corner_name, temp_c, options))
    proc = subprocess.run(
        ["ngspice", "-b", deck_path.name],
        capture_output=True,
        text=True,
        cwd=deck_dir,
        check=False,
    )
    output = proc.stdout + "\n" + proc.stderr
    (log_dir / f"{name}.log").write_text(output)
    return (net_name, corner_name, temp_c), name, runner.parse_measurements(output)


def fmt_mv(value: float) -> str:
    return f"{value * 1e3:.4g} mV"


def main() -> int:
    try:
        pdk = find_pdk()
        ngspice_version = runner.ngspice_version()
    except (PdkNotFound, runner.NgspiceMissing) as exc:
        print(exc, file=sys.stderr)
        return 3

    options = list(json.loads(MANIFEST.read_text()).get("options", []))
    deck_dir = CONTROL_DIR / "decks"
    log_dir = CONTROL_DIR / "logs"
    deck_dir.mkdir(exist_ok=True)
    log_dir.mkdir(exist_ok=True)

    jobs = [
        (pdk, options, deck_dir, log_dir, net_name, netlist, corner_name, temp_c)
        for net_name, netlist, _ in NETLISTS
        for corner_name, temp_c, _ in POINTS
    ]
    results: dict[tuple[str, str, float], dict[str, float]] = {}
    with ThreadPoolExecutor(max_workers=min(4, len(jobs))) as pool:
        for key, name, values in pool.map(run_one, jobs):
            wanted = [f"ok{_tag(ms)}" for ms in SAMPLE_MS] + [f"vr{_tag(ms)}" for ms in SAMPLE_MS]
            missing = [w for w in wanted if w not in values]
            if missing:
                print(f"{name}: ngspice produced no value for {', '.join(missing)}", file=sys.stderr)
                return 2
            results[key] = values
            print(f"{name}: ok -> {(log_dir / (name + '.log')).relative_to(REPO_ROOT)}")

    out: list[str] = [
        "# `ok_bo_dip_mv` dead-rail decay control -- generated, do not edit",
        "",
        "Generated by `sim/bias-core-startup/control/run_ok_dip_decay.py`. Re-run it to",
        "regenerate this file, the decks under `decks/` and the raw ngspice logs under",
        "`logs/`. The numbers quoted in `design/bias_core.md` and in the issue #185 PR",
        "are transcribed from here, and from nowhere else.",
        "",
        "One variable: the DUT netlist (`design/netlist/bias_core.spice` vs.",
        "`layout/postlayout/bias_core.spice`). Same fragment, same PDK, same corner",
        "sections, same solver tolerances, same process. The dead-rail window is",
        f"stretched from the parent testbench's 3 ms to 17 ms ({DEAD_RAIL_START_MS:g} ->",
        f"{DEAD_RAIL_START_MS + 17:g} ms) so the discharge is sampled as a CURVE rather than",
        f"at the single {PARENT_SAMPLE_MS:g} ms point `ok_bo_dip_mv` uses.",
        "",
        f"ngspice: {ngspice_version} · PDK: {pdk.variant}@{pdk.version} · harness {HARNESS_VERSION}",
        f"· VDD before the collapse: {VDD_V} V (the parent testbench's supply axis is",
        "degenerate here -- see `ok_dip_decay.spice`).",
        "",
        "## V(BIAS_OK) with the rail held at 0 V",
        "",
        "`t - 33 ms` is time since the rail reached 0 V. The row marked **parent** is the",
        "instant `ok_bo_dip_mv` samples; the parent testbench's window ends at",
        f"{PARENT_WINDOW_END_MS:g} ms and everything below that row is outside it.",
        "",
    ]

    for corner_name, temp_c, label in POINTS:
        out += [
            f"### {label}",
            "",
            "| t | t − 33 ms | schematic export | klt-extracted | ratio |",
            "| ---: | ---: | ---: | ---: | ---: |",
        ]
        for ms in SAMPLE_MS:
            sch = results[("schematic", corner_name, temp_c)][f"ok{_tag(ms)}"]
            ext = results[("extracted", corner_name, temp_c)][f"ok{_tag(ms)}"]
            # A ratio of two sub-millivolt numbers is noise, not a result.
            ratio = f"{ext / sch:.3g}x" if abs(sch) > 1e-3 else "n/a (both < 1 mV)"
            mark = " **(parent)**" if ms == PARENT_SAMPLE_MS else ""
            out.append(
                f"| {ms:g} ms{mark} | {ms - DEAD_RAIL_START_MS:g} ms | "
                f"{fmt_mv(sch)} | {fmt_mv(ext)} | {ratio} |"
            )
        out += [
            "",
            "V(VREF) on the same DUT over the same window, as the control that the *core*"
            " is discharging the same way on both netlists:",
            "",
            "| t | schematic export | klt-extracted |",
            "| ---: | ---: | ---: |",
        ]
        for ms in SAMPLE_MS:
            sch = results[("schematic", corner_name, temp_c)][f"vr{_tag(ms)}"]
            ext = results[("extracted", corner_name, temp_c)][f"vr{_tag(ms)}"]
            out.append(f"| {ms:g} ms | {sch:.5g} V | {ext:.5g} V |")
        out.append("")

    # The two statements the parent issue needs, derived rather than asserted.
    ss = ("ss", -40.0)
    ext_curve = [results[("extracted", *ss)][f"ok{_tag(ms)}"] for ms in SAMPLE_MS]
    sch_curve = [results[("schematic", *ss)][f"ok{_tag(ms)}"] for ms in SAMPLE_MS]
    monotonic = all(b <= a + 1e-9 for a, b in zip(ext_curve, ext_curve[1:]))
    ext_at_end = ext_curve[-1]
    sch_at_parent = results[("schematic", *ss)][f"ok{_tag(PARENT_SAMPLE_MS)}"]
    ext_at_parent = results[("extracted", *ss)][f"ok{_tag(PARENT_SAMPLE_MS)}"]

    # How far apart the two netlists' VREF discharge curves run, over every
    # sample of every corner -- derived, so the claim below cannot drift.
    vref_gap = max(
        abs(
            results[("extracted", corner_name, temp_c)][f"vr{_tag(ms)}"]
            - results[("schematic", corner_name, temp_c)][f"vr{_tag(ms)}"]
        )
        for corner_name, temp_c, _ in POINTS
        for ms in SAMPLE_MS
    )
    vref_gap_ss = max(
        abs(results[("extracted", *ss)][f"vr{_tag(ms)}"] - results[("schematic", *ss)][f"vr{_tag(ms)}"])
        for ms in SAMPLE_MS
    )

    out += [
        "## What this settles",
        "",
        f"1. **The extracted node is not stuck.** Its discharge at {ss[0]}/{ss[1]:g} C is "
        f"monotonically falling across all {len(SAMPLE_MS)} samples: "
        f"{'confirmed' if monotonic else 'NOT confirmed -- see the table above'}, "
        f"{fmt_mv(ext_curve[0])} at +0.5 ms down to {fmt_mv(ext_at_end)} at +17 ms. "
        "It is the same monotonic discharge as the schematic export, on a longer time "
        "constant -- not a held stale valid.",
        f"2. **The time constant, not the endpoint, is what moved.** At the parent "
        f"testbench's own sample instant the two netlists read {fmt_mv(sch_at_parent)} "
        f"(schematic) and {fmt_mv(ext_at_parent)} (extracted), a factor of "
        f"{ext_at_parent / sch_at_parent:.3g}; the extracted node needs roughly the whole "
        "17 ms window to reach the level the schematic export reaches in 2 ms.",
        f"3. **The core's own discharge is not what moved.** Over the same window V(VREF) "
        f"on the same DUT differs between the two netlists by at most {vref_gap * 1e3:.0f} mV "
        f"anywhere on the grid sampled here ({vref_gap_ss * 1e3:.1f} mV at "
        f"{ss[0]}/{ss[1]:g} C, the failing family), against a `BIAS_OK` difference that "
        f"reaches {(ext_at_parent - sch_at_parent) * 1e3:.0f} mV at the same instant and "
        "the same corner. The reference core gives up its charge at essentially the same "
        "rate on both netlists; what changed by an order of magnitude is the "
        "`BIAS_OK`/`NOKX` output net's own parasitic RC. (At tt/+27 C both `BIAS_OK` "
        "readings are sub-millivolt on both netlists -- that corner is a reference point "
        "showing the check has nothing to measure where it passes, not a second data "
        "point about the mechanism.)",
        "",
    ]

    (CONTROL_DIR / "dip_results.md").write_text("\n".join(out))
    print(f"wrote {(CONTROL_DIR / 'dip_results.md').relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
