#!/usr/bin/env python3
"""One-variable ``gmin`` control for sim/bias-core-startup/.

    python3 sim/bias-core-startup/control/run_gmin_control.py

Composes TWO ngspice decks from ``gmin_control.spice`` + the exported
``design/netlist/bias_core.spice``, identical in every line except a single
``.options gmin=1e-9``, runs a plain ``op`` on each at tt / -40 C /
VDD = 3.3 V, and writes:

    decks/gmin-default.spice   the exact deck as run (ngspice default gmin)
    decks/gmin-1e-9.spice      the exact deck as run (the superseded aid)
    logs/gmin-default.log      raw ngspice output, verbatim
    logs/gmin-1e-9.log         raw ngspice output, verbatim
    results.md                 the comparison table, generated from those logs

This is the control experiment behind design/bias_core.md's "Resolved: the
BIAS_OK quasi-static failure was a testbench artefact" section. It is a
diagnosis of the superseded record `20260801-111049-bc599be`, not a recorded
PVT result: a 2-point control on one corner is not evidence about the corner
grid, so it deliberately does NOT go through sim/run_corners.py and does NOT
mint a record under ../records/. The corner-grid evidence is the 81-point
transient record there; this exists so that the *diagnosis* is reproducible
instead of transcribed. See sim/README.md for the distinction.

Everything except ``gmin`` is held fixed by construction: both decks are
composed from the same fragment, in the same process, from the same PDK, with
the corner sections and solver tolerances read from the harness and from
../testbench/tb.json rather than restated here.

Stdlib only, no virtualenv required.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import textwrap
from pathlib import Path

CONTROL_DIR = Path(__file__).resolve().parent
EXPERIMENT_DIR = CONTROL_DIR.parent
REPO_ROOT = CONTROL_DIR.parents[2]

sys.path.insert(0, str(REPO_ROOT / "sim"))

from harness import HARNESS_VERSION, corners as corners_mod, runner  # noqa: E402
from harness.pdk import PdkNotFound, find_pdk  # noqa: E402

# The one PVT point the control is taken at. tt / -40 C is where the
# superseded record's own BIAS_OK reading was taken; 3.3 V is nominal.
CORNER = "tt"
TEMP_C = -40.0
VDD_V = 3.3

FRAGMENT = CONTROL_DIR / "gmin_control.spice"
DUT_NETLIST = REPO_ROOT / "design" / "netlist" / "bias_core.spice"
MANIFEST = EXPERIMENT_DIR / "testbench" / "tb.json"

# node / device probes, in the order the results table presents them
PROBES: list[tuple[str, str, str]] = [
    ("v(xdut.noko)", "V(NOKO)", "settle comparator output"),
    ("v(xdut.nokl)", "V(NOKL)", "its diode-load reference"),
    ("v(xdut.nokx)", "V(NOKX)", "threshold-stage output"),
    ("v(bias_ok)", "BIAS_OK", "the flag"),
    ("v(vref)", "VREF", "the reference"),
    ("@m.xdut.xmoka.m0[id]", "I(XMOKA)", "input pair, gate NA"),
    ("@m.xdut.xmokb.m0[id]", "I(XMOKB)", "input pair, gate NBTOP"),
    ("@m.xdut.xmol1.m0[id]", "I(XMOL1)", "diode load, mirrors XMOKB"),
    ("@m.xdut.xmol2.m0[id]", "I(XMOL2)", "mirror output, loads XMOKA"),
]

VARIANTS: list[tuple[str, str | None, str]] = [
    ("gmin-default", None, "ngspice default (`gmin = 1e-12`)"),
    ("gmin-1e-9", "1e-9", "the superseded deck (`gmin = 1e-9`)"),
]

_PRINT_RE = re.compile(r"^\s*(\S+)\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)\s*$")

# The paths this script itself regenerates -- see git_describe()'s use below.
GENERATED = tuple(
    str((CONTROL_DIR / name).relative_to(REPO_ROOT)) for name in ("results.md", "decks", "logs")
)


def compose_deck(pdk, gmin: str | None, options: list[str], deck_dir: Path) -> str:
    """Build one complete deck. The ONLY variable across calls is ``gmin``.

    Repo-internal ``.include`` paths are written relative to ``deck_dir`` so a
    committed deck is not tied to the checkout it happened to be generated in;
    the PDK's own paths are absolute because the PDK lives outside the repo
    and the harness resolves it per machine.
    """
    corner = corners_mod.CORNERS[CORNER]
    fragment_rel = os.path.relpath(FRAGMENT, deck_dir)
    dut_rel = os.path.relpath(DUT_NETLIST, deck_dir)
    lines = [
        f"* bias-core-startup gmin control @ {CORNER} / {TEMP_C} C / {VDD_V} V"
        " -- GENERATED by run_gmin_control.py, do not edit",
        f"* gmin: {'ngspice default' if gmin is None else gmin}"
        "   (the one and only difference between the two decks)",
        f"* pdk={pdk.variant}@{pdk.version}",
        "",
        f".param vdd_val={VDD_V!r}",
        "",
        f'.include "{pdk.design_include}"',
    ]
    lines += [f'.lib "{pdk.model_lib}" {section}' for section in corner.sections]
    lines += ["", f".temp {TEMP_C!r}"]
    lines += [f".options {option}" for option in options]
    if gmin is not None:
        lines.append(f".options gmin={gmin}")
    lines += [
        "",
        f'.include "{fragment_rel}"',
        f'.include "{dut_rel}"',
        "",
        ".control",
        "set numdgt=10",
        "set noaskquit",
        "op",
    ]
    lines += [f"print {expr}" for expr, _, _ in PROBES]
    lines += [".endc", ".end", ""]
    return "\n".join(lines)


def parse_prints(text: str) -> dict[str, float]:
    found: dict[str, float] = {}
    for line in text.splitlines():
        match = _PRINT_RE.match(line)
        if match:
            try:
                found[match.group(1)] = float(match.group(2))
            except ValueError:  # pragma: no cover - regex already constrains this
                continue
    return found


def fmt(expr: str, value: float) -> str:
    """Volts to 4 significant decimals, currents in nA to 3 decimals."""
    if expr.startswith("@"):
        return f"{value * 1e9:.3f} nA"
    if abs(value) < 1e-3:
        return f"{value * 1e6:.2f} uV"
    return f"{value:.10g} V"


def main() -> int:
    try:
        pdk = find_pdk()
        ngspice_version = runner.ngspice_version()
    except (PdkNotFound, runner.NgspiceMissing) as exc:
        print(exc, file=sys.stderr)
        return 3

    options = list(json.loads(MANIFEST.read_text()).get("options", []))
    deck_dir = CONTROL_DIR / "decks"
    log_dir = CONTROL_DIR / "logs"
    deck_dir.mkdir(exist_ok=True)
    log_dir.mkdir(exist_ok=True)

    results: dict[str, dict[str, float]] = {}
    for name, gmin, _label in VARIANTS:
        deck_path = deck_dir / f"{name}.spice"
        log_path = log_dir / f"{name}.log"
        deck_path.write_text(compose_deck(pdk, gmin, options, deck_dir))
        proc = subprocess.run(
            ["ngspice", "-b", deck_path.name],
            capture_output=True,
            text=True,
            cwd=deck_dir,
            check=False,
        )
        output = proc.stdout + "\n" + proc.stderr
        log_path.write_text(output)
        values = parse_prints(output)
        missing = [expr for expr, _, _ in PROBES if expr not in values]
        if missing:
            print(f"{name}: ngspice produced no value for {', '.join(missing)}", file=sys.stderr)
            print(output, file=sys.stderr)
            return 2
        results[name] = values
        print(f"{name}: ok -> {log_path.relative_to(REPO_ROOT)}")

    default, elevated = results["gmin-default"], results["gmin-1e-9"]
    signal_na = (default["@m.xdut.xmoka.m0[id]"] - default["@m.xdut.xmokb.m0[id]"]) * 1e9
    signal_elevated_na = (
        elevated["@m.xdut.xmoka.m0[id]"] - elevated["@m.xdut.xmokb.m0[id]"]
    ) * 1e9
    excess_l1_na = (elevated["@m.xdut.xmol1.m0[id]"] - elevated["@m.xdut.xmokb.m0[id]"]) * 1e9
    excess_l2_na = (elevated["@m.xdut.xmol2.m0[id]"] - elevated["@m.xdut.xmoka.m0[id]"]) * 1e9
    default_excess_l1_na = (
        default["@m.xdut.xmol1.m0[id]"] - default["@m.xdut.xmokb.m0[id]"]
    ) * 1e9
    default_excess_l2_na = (
        default["@m.xdut.xmol2.m0[id]"] - default["@m.xdut.xmoka.m0[id]"]
    ) * 1e9
    # gmin is a conductance to ground across each junction: V x 1 nS amperes,
    # which in nA is numerically the node voltage.
    noko_gmin_na = elevated["v(xdut.noko)"]

    table = [
        "| | " + " | ".join(label for _, _, label in VARIANTS) + " |",
        "| --- | ---: | ---: |",
    ]
    for expr, label, note in PROBES:
        cells = " | ".join(fmt(expr, results[name][expr]) for name, _, _ in VARIANTS)
        table.append(f"| `{label}` -- {note} | {cells} |")

    findings = [
        textwrap.fill(text, width=76, initial_indent="- ", subsequent_indent="  ")
        for text in (
            f"The comparator's real signal is `I(XMOKA) - I(XMOKB)` = "
            f"**{signal_na:+.3f} nA** at the default `gmin`, between two branches of "
            f"~{default['@m.xdut.xmoka.m0[id]'] * 1e9:.1f} nA. There the diode loads "
            f"carry what the pair delivers to three digits (excess of "
            f"{default_excess_l1_na:+.4f} nA on `NOKL`, {default_excess_l2_na:+.4f} nA "
            f"on `NOKO`), so the comparator sees only its own signal and `NOKO` "
            f"resolves high.",
            f"At `gmin = 1e-9` the loads carry **{excess_l1_na:.3f} nA** and "
            f"**{excess_l2_na:.3f} nA** more than the pair delivers. The "
            f"**{excess_l1_na - excess_l2_na:.3f} nA** difference between those two "
            f"excesses is the unbalanced part: `XMOKC`'s drain junction hangs on "
            f"`NOKO` with no counterpart on `NOKL` (`V(NOKO)` x 1 nS = "
            f"{noko_gmin_na:.3f} nA). It exceeds the {signal_elevated_na:.3f} nA the "
            f"pair delivers at that perturbed operating point, and is more than twice "
            f"the {signal_na:.3f} nA of real signal at the true one, so the comparator "
            f"lands on the wrong side.",
            f"`VREF` moves "
            f"{(elevated['v(vref)'] - default['v(vref)']) / default['v(vref)'] * 100:+.1f} % "
            f"between the two columns: the same aid acting on the main loop.",
        )
    ]

    body = f"""# `gmin` control -- generated, do not edit

Generated by `sim/bias-core-startup/control/run_gmin_control.py`. Re-run it to
regenerate this file, the two decks under `decks/` and the two raw ngspice logs
under `logs/`. The numbers quoted in `design/bias_core.md`,
`../testbench/stimulus.spice` and `../testbench/tb.json` are transcribed from
here, and from nowhere else.

One variable: `.options gmin`. Both decks are composed from
`gmin_control.spice` + `design/netlist/bias_core.spice` in the same process,
at {CORNER} / {TEMP_C:g} C / VDD = {VDD_V:g} V, plain `op`.

## Result

{chr(10).join(table)}

Currents are the internal `m0` drain currents of the PDK FET subcircuits
(`@m.xdut.<inst>.m0[id]`), signed as ngspice reports them; the pFET pair reads
positive here because `id` is taken at the drain terminal into the device.

## What the numbers say

{chr(10).join(findings)}

## Environment

- PDK: {pdk.variant} @ open_pdks `{pdk.version}` ({pdk.path}, found via {pdk.source})
- ngspice: {ngspice_version}
- Harness: sim/harness {HARNESS_VERSION} (corner sections and solver options only), python {sys.version.split()[0]}
- git: `{runner.git_describe(REPO_ROOT, GENERATED)}`
- Corner sections: {' '.join(corners_mod.CORNERS[CORNER].sections)}
- Solver options (from `../testbench/tb.json`): {' '.join(options)}
- `gmin_control.spice` sha256: `{runner.sha256_file(FRAGMENT)}`
- `design/netlist/bias_core.spice` sha256: `{runner.sha256_file(DUT_NETLIST)}`
"""
    (CONTROL_DIR / "results.md").write_text(body)
    print(f"wrote {(CONTROL_DIR / 'results.md').relative_to(REPO_ROOT)}")
    print(f"signal at default gmin: {signal_na:+.3f} nA")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
