#!/usr/bin/env python3
"""Assemble testbench netlist fragments from committed sources.

    python3 sim/build_tb.py            # (re)generate every fragment
    python3 sim/build_tb.py --check    # verify each is current; write nothing

A generated fragment is ``<experiment>/testbench/stimulus.spice`` followed by a
verbatim copy of one or more ``design/netlist/<cell>.spice`` exports.

Why generate instead of ``.include``: the corner runner rejects ``.include``
inside a fragment (``sim/harness/README.md``), so the device under test has to
be *inlined*. Inlining by hand would let the evidence trail drift silently away
from the schematic -- exactly the failure the append-only convention exists to
prevent. So the fragment is generated, carries each source's sha256 in its
header, and ``--check`` fails if it is stale.

``design/netlist.py --check`` already guarantees the exported netlist matches
the schematic, so the two checks together tie a record back to its ``.sch``.
Unlike ``netlist.py``, this script needs neither xschem nor the PDK, so it is
safe to run in the headless CI job.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SIM = REPO_ROOT / "sim"
NETLIST_DIR = REPO_ROOT / "design" / "netlist"

#: experiment slug -> (generated fragment name, DUT cells inlined after the stimulus)
FRAGMENTS: dict[str, tuple[str, tuple[str, ...]]] = {
    "temp-core-designer-check": ("tb_temp_core.spice", ("temp_core",)),
    "temp-core-startup": ("tb_temp_core_startup.spice", ("temp_core",)),
    "por-comparator-designer-check": ("tb_por_comparator.spice", ("por_comparator",)),
    "por-output-chain-pulse": ("tb_por_pulse.spice", ("por_output_chain",)),
    "por-output-chain-deglitch": ("tb_por_deglitch.spice", ("por_output_chain",)),
    "por-output-chain-floor": ("tb_por_floor.spice", ("por_output_chain",)),
    "bias-core-designer-check": ("tb_bias_core.spice", ("bias_core",)),
    "bias-core-startup": ("tb_bias_core_startup.spice", ("bias_core",)),
    "bias-core-ibias-sharing": (
        "tb_ibias_sharing.spice",
        ("bias_core", "temp_core", "por_comparator"),
    ),
    # temp_por_top.spice already carries every sub-circuit definition the top
    # level instantiates, so one cell here is the whole four-cell assembly.
    "temp-por-top-release": ("tb_temp_por_top.spice", ("temp_por_top",)),
}


def build(slug: str) -> str:
    fragment_name, cells = FRAGMENTS[slug]
    stimulus = SIM / slug / "testbench" / "stimulus.spice"
    header = [
        f"* {fragment_name.removesuffix('.spice')} -- GENERATED by sim/build_tb.py",
        "* Do not edit. Sources:",
        f"*   sim/{slug}/testbench/stimulus.spice",
    ]
    bodies = []
    for cell in cells:
        text = (NETLIST_DIR / f"{cell}.spice").read_text()
        digest = hashlib.sha256(text.encode()).hexdigest()
        header.append(f"*   design/netlist/{cell}.spice  (sha256 {digest})")
        bodies.append(text)
    header += ["* Regenerate with:", "*   python3 sim/build_tb.py", "", ""]
    return "\n".join(header) + stimulus.read_text() + "\n" + "\n".join(bodies)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed fragments match their sources; do not write",
    )
    parser.add_argument(
        "experiments",
        nargs="*",
        default=None,
        help=f"experiment slugs to build (default: all of {', '.join(FRAGMENTS)})",
    )
    args = parser.parse_args(argv)

    slugs = args.experiments or sorted(FRAGMENTS)
    unknown = [s for s in slugs if s not in FRAGMENTS]
    if unknown:
        print(f"unknown experiment(s): {', '.join(unknown)}", file=sys.stderr)
        return 2

    failures = 0
    for slug in slugs:
        fragment_name, _ = FRAGMENTS[slug]
        path = SIM / slug / "testbench" / fragment_name
        text = build(slug)
        rel = path.relative_to(REPO_ROOT)
        if args.check:
            if not path.is_file():
                print(f"FAIL {rel}: missing", file=sys.stderr)
                failures += 1
            elif path.read_text() != text:
                print(
                    f"FAIL {rel}: stale -- re-run 'python3 sim/build_tb.py' "
                    "(the stimulus or the exported DUT netlist changed)",
                    file=sys.stderr,
                )
                failures += 1
            else:
                print(f"OK   {rel}")
        else:
            path.write_text(text)
            print(f"wrote {rel}")

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
