#!/usr/bin/env python3
"""Build the **composite post-layout netlist** for each extracted cell.

    python3 layout/composite_netlist.py                # regenerate layout/composite/
    python3 layout/composite_netlist.py --check        # verify committed outputs are current
    python3 layout/composite_netlist.py --cell bias_core
    python3 layout/composite_netlist.py --extract      # re-run klt extract --parasitics (needs klt)

stdlib only; no PDK, no klayout, no ngspice. ``--extract`` shells out to
``klt`` and is the only mode that needs a toolchain.

What a composite netlist is, and what it is not
-----------------------------------------------
``klt extract`` on every cell under ``layout/cells/`` yields a netlist that is
mostly **MOS-only**: the curated ``gf180mcu`` deck now *declares* ``bjt`` /
``resistor`` / ``cap_mim_*`` device classes, but only ``por_output_chain``
(and ``temp_por_top``, which inherits its geometry) draws the MiM marker
geometry those classes need (klayout-tools#314/#315) -- its two MiM caps
extract as real devices, with isolated plate nodes (see ``Netlist.caps``
below). Every other non-MOS device -- the vertical PNPs, poly resistors, and
``temp_core``'s own MiM cap -- is still not in any extraction
(``layout/README.md`` -> "Known deck limits"). ``klt extract --parasitics``
can only ever hang first-order R/C on the nets that exist in the MOS-only
graph.

So "re-run the suite on the extracted netlist" is not a thing that can be done
literally. What *can* be done, and is what this script builds, is a
**composite**:

* every MOS device, every drawn MiM cap, and every parasitic R/C **from the
  layout** (``layout/reports/<cell>/extracted-parasitics.spice``), and
* every other non-MOS device **verbatim from the golden schematic export**
  (``design/netlist/<cell>.spice``), spliced onto the nets the extraction and
  the schematic are proven to share.

**The passive/bipolar bodies are still ideal.** A result taken on a composite
netlist is evidence about *real interconnect parasitics loading a real MOS
topology* -- the sensing core's high-impedance bias/mirror nodes, the POR
chain's switching nodes, the cross-domain routing -- and nothing else. It is
**not** a parasitic-extracted analog core. Every generated netlist repeats
that in its own header, and every ``sim/`` record taken on one must repeat it
in its **Claim** field (CLAUDE.md: "no claim without a testbench"; the spec is
not relaxed to make a result pass).

How the splice knows where to attach
------------------------------------
The layout labels only a handful of nets, so most extracted nets are anonymous
(``$5``, ``$12``, ...). ``layout/README.md`` used to describe ``por_comparator``'s
sense taps as if ``SNS``/``SNSB`` could be found by name in
``extracted.spice``; they cannot -- **no label is drawn on those tracks**, so
the extractor names them positionally and the schematic names survive only on
the reference side of LVS. Splicing at an *assumed* net name would therefore
silently attach a divider to the wrong node.

This script does not assume. It solves the **net correspondence** between the
extracted netlist and ``layout/cells/<cell>.reference.spice`` (the
schematic-derived LVS reference, generated by ``layout/lvs_reference.py``) --
the same correspondence ``klt lvs`` computes internally but does not report
(filed upstream as tool friction). The solver is a colour-refinement /
backtracking graph isomorphism seeded by the pin names both sides agree on,
and it is **verified**, not trusted: the extracted device multiset translated
through the solved mapping must equal the reference device multiset exactly,
the mapping must be a bijection on nets and pins, and every extracted net that
*does* carry a label must land on a reference net of the same name. Any
failure is an exception, not a warning.

Outputs (all committed as evidence, all regenerated wholesale)
--------------------------------------------------------------
``layout/reports/<cell>/extracted-parasitics.spice`` / ``.json``
    ``klt extract --parasitics`` output. Deliberately a *separate* artifact
    from ``extracted.spice`` / ``extract.json``, which ``run_checks.sh`` keeps
    byte-stable for the DRC/LVS repeatability contract.
``layout/composite/<cell>.composite.spice``
    the composite netlist, in ngspice simulation form, with the golden
    ``.subckt`` port list -- a drop-in replacement for
    ``design/netlist/<cell>.spice``.
``layout/composite/<cell>.audit.json``
    per-net provenance (real-MOS+parasitic vs ideal/schematic), the
    parasitics-coverage counters, and the verdicts on ``layout/README.md``'s
    own "Consequences to carry forward" bullets.
``layout/composite/AUDIT.md``
    the same, rendered.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import lvs_reference as ref  # noqa: E402

LAYOUT_DIR = Path(__file__).resolve().parent
REPO_ROOT = LAYOUT_DIR.parent
NETLIST_DIR = REPO_ROOT / "design" / "netlist"
CELLS_DIR = LAYOUT_DIR / "cells"
REPORTS_DIR = LAYOUT_DIR / "reports"
COMPOSITE_DIR = LAYOUT_DIR / "composite"

DECK = "gf180mcu"

#: The extractor hangs each net's lumped capacitance on this suffixed node.
PARASITIC_SUFFIX = "__par"

#: Instance-qualified nets in an assembly reference (``xbias.NB``) become
#: ``xbias__NB`` in the composite netlist: ngspice treats ``.`` as the
#: hierarchy separator, so it must not appear inside a flat node name.
INSTANCE_SEPARATOR = "__"


class CompositeError(Exception):
    pass


# --------------------------------------------------------------------------
# The five cells that have their own layout/reports/<cell>/extract.json.
#
# One entry per cell, same convention as layout/lvs_reference.py's CELLS: the
# manifest is data, not code, so it cannot drift from what is actually drawn
# without the assertions below failing. Everything that can be derived from an
# already-committed artifact (port list, device list, well assignment,
# top_cell_pins) IS derived; only the two things that cannot be are declared:
#
#   ``smoke``   the DC operating-point smoke deck for this cell
#               (layout/composite_smoke.py) -- a cell needs stimulus, and
#               stimulus is a per-cell fact.
#   ``readme``  the "Consequences to carry forward" bullets layout/README.md
#               states for this cell, restated as machine-checkable claims so
#               a stale bullet fails a run instead of only misleading a reader.
# --------------------------------------------------------------------------
CELLS: dict[str, dict] = {
    "bias_core": {
        "note": "the MOS portion of the shared bias/reference core (#68)",
        "readme": [
            {
                "claim": "the three nets that exist only through a resistor "
                "(EC, ER, NZ) are absent from the extraction",
                "nets": ["EC", "ER", "NZ"],
                "extracted": False,
            },
            {
                "claim": "VREF, IBIAS and NB appear with one MOS terminal each",
                "nets": ["VREF", "IBIAS", "NB"],
                "extracted": True,
                "mos_terminals": 1,
            },
        ],
        "smoke": {
            "stimulus": [
                "vsup vdd 0 dc {vdd}",
                "xdut vdd 0 ibias vref bias_ok bias_core",
                "* IBIAS is a source; give it the same diode load the",
                "* sim/bias-core-designer-check/ stimulus uses.",
                "xmld ibias ibias 0 0 nfet_03v3 L=2u W=2u nf=1 m=1",
            ],
            "measure": {
                "vref_v": "v(vref)",
                "vibias_v": "v(ibias)",
                "vbias_ok_v": "v(bias_ok)",
                "iq_ua": "-i(vsup)*1e6",
            },
            "sane": {
                "vref_v": [0.8, 1.6],
                "vibias_v": [0.2, 1.2],
                "vbias_ok_v": [2.5, 3.4],
                "iq_ua": [0.05, 50.0],
            },
        },
    },
    "temp_core": {
        "note": "the PTAT/CTAT sensing core (#71)",
        "readme": [
            {
                "claim": "the PNP array, R2 gain ladder and MiM cap are drawn as "
                "sibling top cells and are outside this compare, so the two nets "
                "they alone own (NC, NZ) are absent from the extraction",
                "nets": ["NC", "NZ"],
                "extracted": False,
            },
            {
                "claim": "the trim-ladder taps T0..T5 are real drawn nets "
                "(the trim switches are MOS and are drawn)",
                "nets": ["T0", "T1", "T2", "T3", "T4", "T5"],
                "extracted": True,
            },
        ],
        "smoke": {
            "stimulus": [
                "vsup vdd 0 dc {vdd}",
                "ven  en  0 dc {vdd}",
                "xdut vdd 0 ibias en ptat ctat temp_core",
                "ibref vdd ibias dc 500n",
                "Rlp ptat 0 1T",
                "Rlc ctat 0 1T",
            ],
            "measure": {
                "vptat_v": "v(ptat)",
                "vctat_v": "v(ctat)",
                "vibias_v": "v(ibias)",
                "iq_ua": "-i(vsup)*1e6",
            },
            "sane": {
                "vptat_v": [0.5, 2.5],
                "vctat_v": [0.3, 0.95],
                "vibias_v": [0.2, 1.2],
                "iq_ua": [0.5, 200.0],
            },
        },
    },
    "por_comparator": {
        "note": "the POR threshold comparator (#69)",
        "readme": [
            {
                "claim": "SNS and SNSB appear with one MOS terminal each "
                "(XMINA's gate, XMHSW's drain)",
                "nets": ["SNS", "SNSB"],
                "extracted": True,
                "mos_terminals": 1,
            },
            {
                "claim": "SNS and SNSB carry no drawn label, so they do NOT appear "
                "under those names anywhere in extracted.spice",
                "nets": ["SNS", "SNSB"],
                "extracted": True,
                "labelled": False,
            },
        ],
        "smoke": {
            "stimulus": [
                "vsup vdd 0 dc {vdd}",
                "vok  bias_ok 0 dc {vdd}",
                "vref vref 0 dc 1.2",
                "ibref vdd ibias dc 500n",
                "xdut vdd 0 ibias vref bias_ok por_raw por_comparator",
            ],
            "measure": {
                "vpor_raw_v": "v(por_raw)",
                "vsns_v": "v(xdut.sns)",
                "vsnsb_v": "v(xdut.snsb)",
                "iq_ua": "-i(vsup)*1e6",
            },
            "sane": {
                # 3.3 V is above the ratified rise threshold, so POR_RAW is
                # released; the divider taps sit between the rails.
                "vpor_raw_v": [2.5, 3.4],
                "vsns_v": [0.8, 2.4],
                "vsnsb_v": [0.05, 1.2],
                "iq_ua": [0.05, 50.0],
            },
        },
    },
    "por_output_chain": {
        "note": "the MOS portion of the reset output chain (#70)",
        "readme": [
            {
                "claim": "NDG and TIM each carry MOS terminals as well as a cap "
                "terminal; the two MiM caps are drawn for real (klayout-tools"
                "#314/#315) and extract as their own isolated-plate devices "
                "(Netlist.caps), so every schematic net still exists on both "
                "sides of the compare via the MOS terminal alone",
                "nets": ["NDG", "TIM"],
                "extracted": True,
            }
        ],
        "smoke": {
            "stimulus": [
                "vsup vdd 0 dc {vdd}",
                "vpor por_raw 0 dc {vdd}",
                "ibref vdd ibias dc 500n",
                "xdut vdd 0 ibias por_raw resetn por_output_chain",
                "Cload resetn 0 5p",
            ],
            "measure": {
                "vresetn_v": "v(resetn)",
                "vibias_v": "v(ibias)",
                "vtim_v": "v(xdut.tim)",
                "iq_ua": "-i(vsup)*1e6",
            },
            "sane": {
                "vresetn_v": [2.5, 3.4],
                "vibias_v": [0.2, 1.2],
                "vtim_v": [-0.05, 3.4],
                "iq_ua": [0.05, 50.0],
            },
        },
    },
    "temp_por_top": {
        "note": "the block-level assembly (#72)",
        "readme": [
            {
                "claim": "every non-MOS device of all four sub-circuits is outside "
                "this compare, so the nets they alone own are absent from the "
                "extraction",
                "nets": [
                    "xbias__EC",
                    "xbias__ER",
                    "xbias__NZ",
                    "xtemp__NC",
                    "xtemp__NZ",
                ],
                "extracted": False,
            },
            {
                "claim": "IBIAS is the one bias net that crosses the domain seam and "
                "it is a real drawn net shared by all four sub-circuits",
                "nets": ["IBIAS"],
                "extracted": True,
            },
        ],
        "smoke": {
            # The one cell that cannot be smoke-tested with a bare `op`. The
            # POR one-shot is a timed element, so a DC solve has no way to
            # reach the released state and parks the block in reset with the
            # sensor off -- a legitimate DC solution, but not one that
            # exercises the netlist. A short rail ramp reaches the settled
            # released state instead, and the operating point is sampled
            # there. The golden schematic netlist is run through the identical
            # deck as a control (layout/composite_smoke.py), so what is
            # compared is like for like.
            "stimulus": [
                "vsup vdd 0 pwl(0 0 1m {vdd} 30m {vdd})",
                "xdut vdd 0 ptat ctat resetn temp_por_top",
                "Cload resetn 0 5p",
                "Rlp ptat 0 1T",
                "Rlc ctat 0 1T",
            ],
            "analyses": [
                "tran 10u 20m",
                "meas tran s_resetn find v(resetn) at=19m",
                "meas tran s_ptat find v(ptat) at=19m",
                "meas tran s_ctat find v(ctat) at=19m",
                "meas tran s_ibias find v(xdut.ibias) at=19m",
                "meas tran s_vref find v(xdut.vref) at=19m",
                "meas tran s_isup avg i(vsup) from=18m to=19m",
                # The one measurement in this whole smoke run that the
                # extracted parasitics can actually move. Their model is one
                # series R into one lumped C per net, so at DC the R carries
                # no current and the C is an open -- every operating point
                # below is parasitic-invariant BY CONSTRUCTION. A switching
                # edge is not: this is where the ~4.8 pF of extracted
                # interconnect capacitance shows up.
                "meas tran s_release when v(resetn)=1.65 rise=1",
            ],
            "measure": {
                "vresetn_v": "s_resetn",
                "vptat_v": "s_ptat",
                "vctat_v": "s_ctat",
                "vibias_v": "s_ibias",
                "vref_v": "s_vref",
                "iq_ua": "-s_isup*1e6",
                "t_release_ms": "s_release*1e3",
            },
            "sane": {
                "vresetn_v": [2.5, 3.4],
                "vptat_v": [0.5, 2.5],
                "vctat_v": [0.3, 0.95],
                "vibias_v": [0.2, 1.2],
                "vref_v": [0.8, 1.6],
                "iq_ua": [0.5, 300.0],
                "t_release_ms": [0.5, 19.0],
            },
        },
    },
}


# ==========================================================================
# SPICE parsing
# ==========================================================================

_UNIT = re.compile(r"^([0-9.eE+-]+)\s*([a-zA-Z]*)$")
_SI = {"": 1.0, "f": 1e-15, "p": 1e-12, "n": 1e-9, "u": 1e-6, "m": 1e-3, "k": 1e3}


def _number(token: str) -> float:
    match = _UNIT.match(token)
    if not match:
        raise CompositeError(f"cannot parse numeric token {token!r}")
    value, suffix = match.groups()
    scale = _SI.get(suffix.lower())
    if scale is None:
        raise CompositeError(f"unsupported unit suffix in {token!r}")
    return float(value) * scale


def _unescape(node: str) -> str:
    """KLayout escapes leading ``$`` in written SPICE node names."""
    return node[1:] if node.startswith("\\") else node


def _cards(text: str) -> list[tuple[str, str]]:
    """``(card, preceding comment)`` with ``+`` continuations joined.

    The writer wraps long lines -- a wide ``.SUBCKT`` pin list, for
    instance -- so a parser that reads physical lines silently loses pins.
    """
    out: list[tuple[str, str]] = []
    comment = ""
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("*"):
            comment = line
            continue
        if line.startswith("+"):
            if not out:
                raise CompositeError("continuation line with nothing to continue")
            out[-1] = (f"{out[-1][0]} {line[1:].strip()}", out[-1][1])
            continue
        out.append((line, comment))
        comment = ""
    return out


class Device:
    """One 4-terminal MOS card, from either side of the compare."""

    __slots__ = ("name", "klass", "nodes", "length", "width", "params", "comment")

    def __init__(self, name, klass, nodes, length, width, params=None, comment=""):
        self.name = name
        self.klass = klass
        self.nodes = list(nodes)  # d g s b
        self.length = length
        self.width = width
        self.params = dict(params or {})
        self.comment = comment

    def key(self, rename=lambda net: net) -> tuple:
        """Order-insensitive identity: source/drain are interchangeable."""
        drain, gate, source, body = (rename(n) for n in self.nodes)
        return (
            self.klass,
            round(self.length, 6),
            round(self.width, 6),
            tuple(sorted((drain, source))),
            gate,
            body,
        )

    def __repr__(self):  # pragma: no cover - debugging aid
        return f"<Device {self.name} {self.klass} {self.nodes}>"


class Netlist:
    """A parsed MOS-plus-parasitics SPICE netlist."""

    def __init__(self, name, ports, devices, parasitics=None, caps=None):
        self.name = name
        self.ports = list(ports)
        self.devices = list(devices)
        self.parasitics = list(parasitics or [])  # (letter, name, n1, n2, value)
        # Real MiM-cap DEVICE cards from an extraction where the cell's caps
        # are drawn (`lvs_reference.CELLS[cell]["caps"]`), as opposed to the
        # interconnect R/C in `parasitics`: (name, node_a, node_b, value_f,
        # klass). `klt` cannot route a capacitor plate onto a net (the same
        # "Known limitation" `lvs_reference.cap_plate_nets` documents), so
        # each plate node is its own isolated net -- never touched by a MOS
        # device -- and is therefore not part of the net-correspondence
        # graph; see `cap_nets`.
        self.caps = list(caps or [])

    @property
    def cap_nets(self) -> set[str]:
        return {node for _name, node_a, node_b, _value, _klass in self.caps for node in (node_a, node_b)}

    @property
    def nets(self) -> list[str]:
        seen: dict[str, None] = {}
        for device in self.devices:
            for node in device.nodes:
                seen.setdefault(node, None)
        for _letter, _name, node_a, node_b, _value in self.parasitics:
            for node in (node_a, node_b):
                if not node.endswith(PARASITIC_SUFFIX):
                    seen.setdefault(node, None)
        for node in self.cap_nets:
            seen.setdefault(node, None)
        for port in self.ports:
            seen.setdefault(port, None)
        return list(seen)

    def terminals(self) -> dict[str, list[tuple[int, str]]]:
        """net -> [(device index, terminal role)]; d/s share the role ``sd``.

        Built from MOS device terminals alone -- not seeded from
        :attr:`nets` -- so an isolated net that no MOS device touches (a
        drawn MiM cap's plate; see :attr:`cap_nets`) is simply absent from
        the graph the net-correspondence solver searches, rather than
        appearing as a spurious zero-terminal node with no counterpart on
        the reference side.
        """
        roles = ("sd", "g", "sd", "b")
        table: dict[str, list[tuple[int, str]]] = {}
        for index, device in enumerate(self.devices):
            for node, role in zip(device.nodes, roles):
                table.setdefault(node, []).append((index, role))
        return table

    def mos_terminal_counts(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for device in self.devices:
            for node in device.nodes:
                counts[node] = counts.get(node, 0) + 1
        return counts


def parse_extracted(path: Path) -> Netlist:
    """Parse a ``klt extract`` SPICE output (with or without ``--parasitics``)."""
    ports: list[str] = []
    devices: list[Device] = []
    parasitics: list[tuple[str, str, str, str, float]] = []
    caps: list[tuple[str, str, str, float, str]] = []
    name = path.stem
    for line, pending_comment in _cards(path.read_text()):
        upper = line.upper()
        if upper.startswith(".SUBCKT"):
            fields = line.split()
            name = fields[1]
            ports = fields[2:]
            continue
        if upper.startswith(".ENDS"):
            continue
        fields = line.split()
        head = fields[0]
        if head[0] in "Mm":
            nodes = [_unescape(n) for n in fields[1:5]]
            klass = fields[5]
            params = {}
            for field in fields[6:]:
                key, _, value = field.partition("=")
                params[key.upper()] = value
            devices.append(
                Device(
                    name=head[1:],
                    klass=klass,
                    nodes=nodes,
                    length=_number(params["L"]) * 1e6,
                    width=_number(params["W"]) * 1e6,
                    params=params,
                    comment=pending_comment,
                )
            )
        elif head[0] in "Cc" and len(fields) == 5:
            # A real MiM-cap DEVICE card (2 nodes, a value, and the deck's
            # class name), from a cell whose caps are drawn -- see
            # `Netlist.caps`. An interconnect-parasitic C card (below) never
            # carries a class name, so the field count alone distinguishes
            # them without needing the manifest here.
            caps.append(
                (
                    head[1:],
                    _unescape(fields[1]),
                    _unescape(fields[2]),
                    float(fields[3]),
                    fields[4],
                )
            )
        elif head[0] in "RrCc":
            parasitics.append(
                (
                    head[0].upper(),
                    head[1:],
                    _unescape(fields[1]),
                    _unescape(fields[2]),
                    float(fields[3]),
                )
            )
        else:
            raise CompositeError(f"{path}: unexpected card {line!r}")
    return Netlist(name, ports, devices, parasitics, caps)


def parse_reference(path: Path) -> Netlist:
    """Parse a ``layout/lvs_reference.py`` output (plain-element MOS only).

    A cell with drawn (real) MiM caps -- ``lvs_reference.build_cap_cards`` --
    trails its ``.reference.spice`` with ``C<n> ...`` cards after the MOS
    ``M``/``MD`` ones. Those caps are already in the extracted half for a
    drawn cell (``extracted.parasitics``, misfiled as an interconnect
    parasitic but numerically correct -- see :func:`_non_mos_cards`'s
    ``drawn_caps``), so this parser -- MOS devices only, same as ``klt``'s own
    curated deck -- skips them rather than mis-reading a 5-field cap card as
    a 4-terminal MOS one.
    """
    ports: list[str] = []
    devices: list[Device] = []
    name = path.stem
    for line, _comment in _cards(path.read_text()):
        upper = line.upper()
        if upper.startswith(".SUBCKT"):
            fields = line.split()
            name = fields[1]
            ports = fields[2:]
            continue
        if upper.startswith(".ENDS"):
            continue
        fields = line.split()
        if fields[0].upper().startswith("C"):
            continue
        params = {}
        for field in fields[6:]:
            key, _, value = field.partition("=")
            params[key.upper()] = value
        devices.append(
            Device(
                name=fields[0],
                klass=fields[5],
                nodes=fields[1:5],
                length=_number(params["L"]) * 1e6,
                width=_number(params["W"]) * 1e6,
                params=params,
            )
        )
    return Netlist(name, ports, devices)


# ==========================================================================
# Net correspondence: extracted net <-> reference (schematic) net
# ==========================================================================


def _refine(netlist: Netlist, seed: dict[str, str], rounds: int, shared: dict) -> dict:
    """One colour-refinement pass set; returns net -> integer colour.

    ``shared`` is the colour dictionary both netlists intern into, so a colour
    means the same thing on both sides -- that is what makes the two
    partitions comparable at all.
    """

    def intern(token) -> int:
        return shared.setdefault(token, len(shared))

    terminals = netlist.terminals()
    colour = {net: intern(("seed", seed.get(net, ""))) for net in terminals}
    for _ in range(rounds):
        device_colour = []
        for device in netlist.devices:
            drain, gate, source, body = device.nodes
            device_colour.append(
                intern(
                    (
                        "dev",
                        device.klass,
                        round(device.length, 6),
                        round(device.width, 6),
                        tuple(sorted((colour[drain], colour[source]))),
                        colour[gate],
                        colour[body],
                    )
                )
            )
        updated = {}
        for net, terms in terminals.items():
            updated[net] = intern(
                (
                    "net",
                    colour[net],
                    tuple(sorted((device_colour[i], role) for i, role in terms)),
                )
            )
        if len(set(updated.values())) == len(set(colour.values())):
            colour = updated
            break
        colour = updated
    return colour


def _classes(colour: dict[str, int]) -> dict[int, list[str]]:
    out: dict[int, list[str]] = {}
    for net, value in colour.items():
        out.setdefault(value, []).append(net)
    for nets in out.values():
        nets.sort()
    return out


def solve_correspondence(
    extracted: Netlist, reference: Netlist, pin_pairs: dict[str, str]
) -> dict[str, str]:
    """Solve extracted-net -> reference-net, seeded by the agreed pin names.

    Colour refinement first; anything it leaves ambiguous is resolved by
    backtracking (guess one pair, re-refine, recurse). The result is verified
    by the caller against the device multiset -- a wrong guess cannot survive
    that, so the search cannot silently return a plausible-but-wrong answer.
    """
    rounds = max(len(extracted.nets), len(reference.nets)) + 2

    def attempt(forced: dict[str, str], depth: int) -> dict[str, str] | None:
        if depth > len(extracted.nets) + 2:  # pragma: no cover - safety net
            return None
        shared: dict = {}
        seed_extracted = {net: f"#{i}" for i, net in enumerate(sorted(forced))}
        seed_reference = {
            forced[net]: f"#{i}" for i, net in enumerate(sorted(forced))
        }
        colour_e = _refine(extracted, seed_extracted, rounds, shared)
        colour_r = _refine(reference, seed_reference, rounds, shared)
        classes_e = _classes(colour_e)
        classes_r = _classes(colour_r)
        if set(classes_e) != set(classes_r):
            return None
        mapping: dict[str, str] = {}
        ambiguous: list[int] = []
        for value, nets_e in classes_e.items():
            nets_r = classes_r[value]
            if len(nets_e) != len(nets_r):
                return None
            if len(nets_e) == 1:
                mapping[nets_e[0]] = nets_r[0]
            else:
                ambiguous.append(value)
        if not ambiguous:
            return mapping
        # Guess inside the smallest ambiguous class and re-refine.
        value = min(ambiguous, key=lambda v: (len(classes_e[v]), v))
        net_e = classes_e[value][0]
        for net_r in classes_r[value]:
            deeper = dict(forced)
            deeper[net_e] = net_r
            result = attempt(deeper, depth + 1)
            if result is not None:
                return result
        return None

    mapping = attempt(dict(pin_pairs), 0)
    if mapping is None:
        raise CompositeError(
            "could not solve the extracted<->reference net correspondence; "
            "the two netlists are not isomorphic under the pin seeding "
            "(re-run layout/run_checks.sh -- LVS should be failing too)"
        )
    return mapping


def pin_correspondence(extracted: Netlist, reference: Netlist) -> dict[str, str]:
    """Match extracted pins to reference ports by name.

    Extraction joins two labels drawn on one net with ``|`` (``EN|RESETn``),
    so an extracted pin is matched on any of its aliases. Requires a perfect
    matching -- a pin set that does not line up means the committed LVS run
    and this script are looking at different things.
    """
    available = set(reference.ports)
    pairs: dict[str, str] = {}
    for pin in extracted.ports:
        aliases = [alias for alias in pin.split("|") if alias in available]
        if len(aliases) != 1:
            raise CompositeError(
                f"extracted pin {pin!r} matches {len(aliases)} reference port(s) "
                f"{aliases}; reference ports are {sorted(reference.ports)}"
            )
        pairs[pin] = aliases[0]
        available.discard(aliases[0])
    if available:
        raise CompositeError(
            f"reference port(s) {sorted(available)} have no extracted pin"
        )
    return pairs


def verify_correspondence(
    extracted: Netlist, reference: Netlist, mapping: dict[str, str]
) -> None:
    """Prove the mapping, rather than trusting the solver that produced it.

    A drawn MiM cap's isolated plate nets (:attr:`Netlist.cap_nets`) are
    real extracted nets but touch no MOS device, so they never enter the
    net-correspondence graph (:meth:`Netlist.terminals`) and are excluded
    from the count here too -- they are emitted directly from their own
    extracted node names (see ``build_cell``), not through this mapping.
    """
    solved_nets = set(extracted.nets) - extracted.cap_nets
    if set(mapping) != solved_nets:
        raise CompositeError(
            f"mapping covers {len(mapping)} of {len(solved_nets)} extracted "
            "nets needing correspondence"
        )
    if len(set(mapping.values())) != len(mapping):
        raise CompositeError("mapping is not injective -- two nets would be shorted")
    if set(mapping.values()) != set(reference.nets) | set(reference.ports):
        missing = (set(reference.nets) | set(reference.ports)) - set(mapping.values())
        extra = set(mapping.values()) - (set(reference.nets) | set(reference.ports))
        raise CompositeError(
            f"mapping is not onto the reference nets (missing {sorted(missing)}, "
            f"unexpected {sorted(extra)})"
        )

    left = sorted(device.key(lambda net: mapping[net]) for device in extracted.devices)
    right = sorted(device.key() for device in reference.devices)
    if left != right:
        raise CompositeError(
            "the extracted device list, translated through the solved net "
            "mapping, is not the reference device list -- the correspondence "
            "is wrong (or LVS is no longer a match)"
        )

    # A net the layout actually labels must land on the reference net of the
    # same name. This is an independent check on the topological solve: it
    # uses information (the drawn label) the solver was never given for
    # anything but the pins.
    for net_e, net_r in mapping.items():
        if net_e.startswith("$"):
            continue
        for alias in net_e.split("|"):
            tail = net_r.rsplit(".", 1)[-1]
            if alias == tail:
                break
        else:
            raise CompositeError(
                f"extracted net {net_e!r} carries a drawn label but the solved "
                f"correspondence puts it on reference net {net_r!r}"
            )


# ==========================================================================
# Reference-net -> schematic-net, and the non-MOS devices to splice
# ==========================================================================


def _golden_devices(cell_source: str, subckt: str) -> dict[str, dict]:
    text = (NETLIST_DIR / cell_source).read_text()
    body = ref.subckt_body(text, subckt)
    return ref.parse_devices(body)


def check_every_golden_device_is_accounted_for(cell: str) -> None:
    """No golden device may fall between the two halves of the composite.

    A MOS device the layout manifest does not list would be dropped from the
    extracted half (it is not drawn) *and* skipped by the spliced half (it is
    a MOS card), so it would vanish silently. ``lvs_reference.build_cards``
    checks the other direction -- a manifest device missing from the golden
    netlist -- so between them every device in the schematic is either drawn
    or deliberately spliced.
    """

    def check(spec: dict) -> None:
        devices = _golden_devices(spec["source"], spec["subckt"])
        listed = set(spec["devices"])
        missing = sorted(set(devices) - listed)
        if missing:
            raise CompositeError(
                f"{cell}: golden MOS device(s) {', '.join(missing)} are in "
                f"design/netlist/{spec['source']} but not in "
                "lvs_reference.CELLS -- they would be in neither half of the "
                "composite netlist"
            )

    spec = ref.CELLS[cell]
    if "assembly" in spec:
        for _inst, sub_cell, _rename in ref.instance_renames(cell):
            check(ref.CELLS[sub_cell])
    else:
        check(spec)


def _non_mos_cards(
    cell_source: str, subckt: str, drawn_caps: frozenset[str] = frozenset()
) -> list[tuple[str, list[str], str]]:
    """(name, nodes, trailing text) for every non-MOS card in a golden subckt.

    ``drawn_caps`` is a manifest's own ``caps`` list (``lvs_reference.CELLS``):
    the golden MiM cards that a *drawn* cell now instantiates for real
    (klayout-tools#314/#315; ``lvs_reference.build_cap_cards``). Those are
    already in the extracted half via ``extracted-parasitics.spice`` -- they
    are excluded here, not spliced, or the composite netlist would carry the
    same capacitor twice: once real, once ideal.
    """
    text = (NETLIST_DIR / cell_source).read_text()
    cards: list[tuple[str, list[str], str]] = []
    for line in ref.subckt_body(text, subckt):
        fields = line.split()
        if not fields[0].upper().startswith("X"):
            continue
        if fields[0] in drawn_caps:
            continue
        # The MOS cards are the ones lvs_reference knows how to convert; every
        # other X card is a device this deck cannot extract.
        if any(field in ref.DEVICE_CLASS for field in fields[1:]):
            continue
        model_index = None
        for index, field in enumerate(fields[1:], start=1):
            if "=" not in field:
                model_index = index
        if model_index is None:
            raise CompositeError(f"cannot find the model name in {line!r}")
        nodes = fields[1:model_index]
        trailing = " ".join(fields[model_index:])
        cards.append((fields[0], nodes, trailing))
    return cards


def body_aliases(cell: str) -> dict[str, str]:
    """Reference body-net name -> the schematic net it stands for.

    ``lvs_reference.py`` rewrites every NMOS body onto the deck's global
    substrate net and every PMOS body onto a per-drawn-well net, because that
    is all the deck can see. A simulation netlist cannot leave them there --
    an anonymous well net is a floating body. This restores the schematic's
    own body nodes, and is the one place the composite netlist takes
    connectivity from the schematic for a device the layout *does* draw. It is
    called out in the generated header for exactly that reason.
    """
    aliases: dict[str, str] = {}

    def record(body_ref: str, body_schematic: str) -> None:
        previous = aliases.setdefault(body_ref, body_schematic)
        if previous != body_schematic:
            raise CompositeError(
                f"{cell}: body net {body_ref!r} stands for both {previous!r} "
                f"and {body_schematic!r} in the schematic"
            )

    def walk(spec: dict, rename=lambda net: net) -> None:
        devices = _golden_devices(spec["source"], spec["subckt"])
        well_of = {
            member: well
            for well, members in spec.get("wells", {}).items()
            for member in members
        }
        for name in spec["devices"]:
            device = devices[name]
            _letter, klass = ref.DEVICE_CLASS[device["model"]]
            body_ref = ref.SUBSTRATE_NET if klass == "nfet" else well_of[name]
            record(rename(body_ref), rename(device["nodes"][3]))
        # A drawn edge dummy is not in the schematic, so it contributes no
        # body alias of its own -- it sits in a well some real device already
        # resolved. A dummy in a well nothing else occupies would leave that
        # body floating in simulation, so that is an error, not a default.
        for dummy in spec.get("dummies", []):
            if dummy["class"] == "nfet":
                continue
            if rename(dummy["well"]) not in aliases:
                raise CompositeError(
                    f"{cell}: drawn dummy sits in well {dummy['well']!r}, which "
                    "no schematic device occupies -- nothing says what to tie "
                    "its body to"
                )

    spec = ref.CELLS[cell]
    if "assembly" in spec:
        for _inst, sub_cell, rename in ref.instance_renames(cell):
            walk(ref.CELLS[sub_cell], rename)
    else:
        walk(spec)
    return aliases


def cap_plate_pairs(cell: str) -> dict[float, tuple[str, str]]:
    """Drawn-cap value -> the (real net, real net) its two plates stand for.

    Same situation as :func:`body_aliases`, for the other place ``klt``
    cannot see a connection it is physically there: a capacitor's plates
    extract as their own isolated, self-connected nodes (``klt``'s
    ``CapacitorDevice`` "Known limitation"; also why
    ``lvs_reference.cap_plate_nets`` names the LVS reference's plate nodes
    ``XCDG.NDG`` rather than ``NDG``). A composite netlist cannot leave a
    drawn cap floating -- it would carry no capacitive loading on the real
    net at all, defeating the entire point of drawing it -- so this restores
    the schematic's own two nets for each drawn cap, keyed by value.

    Keyed by value rather than by instance because that is all the
    extraction can tell two identical parallel units apart by: their plate
    nodes are isolated, so nothing in ``extracted-parasitics.spice``
    distinguishes ``XCTIM``'s unit 1 from unit 3 either (the reference's own
    ``.N`` unit numbering is arbitrary for the same reason). A capacitor is
    non-polarized, so within one value class every unit tying the same net
    pair is electrically interchangeable; two golden caps sharing a value
    but wiring different net pairs is refused rather than guessed at.
    """

    def golden_pairs(spec: dict, rename=lambda net: net) -> dict[float, tuple[str, str]]:
        names = spec.get("caps", [])
        if not names:
            return {}
        source = NETLIST_DIR / spec["source"]
        caps = ref.parse_capacitors(ref.subckt_body(source.read_text(), spec["subckt"]))
        pairs: dict[float, tuple[str, str]] = {}
        for name in names:
            cap = caps[name]
            width_um = ref.to_um(cap["params"]["c_width"])
            length_um = ref.to_um(cap["params"]["c_length"])
            value = width_um * length_um * ref.MIM_AREA_CAP_F_UM2
            key = round(value, 21)
            node_a, node_b = (composite_name(rename(node)) for node in cap["nodes"])
            previous = pairs.get(key)
            if previous is not None and previous not in ((node_a, node_b), (node_b, node_a)):
                raise CompositeError(
                    f"{cell}: drawn caps {value:.6g} F apart wire different net "
                    f"pairs ({previous} vs {(node_a, node_b)}) -- cannot auto-wire "
                    "extracted plates by value alone"
                )
            pairs[key] = (node_a, node_b)
        return pairs

    spec = ref.CELLS[cell]
    if "assembly" in spec:
        pairs: dict[float, tuple[str, str]] = {}
        for _inst, sub_cell, rename in ref.instance_renames(cell):
            for key, value_pair in golden_pairs(ref.CELLS[sub_cell], rename).items():
                previous = pairs.get(key)
                if previous is not None and previous not in (
                    value_pair,
                    value_pair[::-1],
                ):
                    raise CompositeError(
                        f"{cell}: drawn caps {key:.6g} F apart wire different net "
                        f"pairs ({previous} vs {value_pair}) across sub-cells -- "
                        "cannot auto-wire extracted plates by value alone"
                    )
                pairs[key] = value_pair
        return pairs
    return golden_pairs(spec)


def drawn_cap_unit_count(cell: str) -> int:
    """How many drawn-cap DEVICES (post ``m=`` multiplier) a cell's manifest
    declares -- what :func:`build_cell` requires ``extracted.caps`` to equal
    exactly, the same "every golden device accounted for" guarantee
    :func:`check_every_golden_device_is_accounted_for` gives the MOS half.
    """

    def count(spec: dict) -> int:
        names = spec.get("caps", [])
        if not names:
            return 0
        source = NETLIST_DIR / spec["source"]
        caps = ref.parse_capacitors(ref.subckt_body(source.read_text(), spec["subckt"]))
        return sum(ref.cap_units(caps[name]) for name in names)

    spec = ref.CELLS[cell]
    if "assembly" in spec:
        return sum(
            count(ref.CELLS[sub_cell])
            for _inst, sub_cell, _rename in ref.instance_renames(cell)
        )
    return count(spec)


def composite_name(net: str) -> str:
    return net.replace(".", INSTANCE_SEPARATOR)


def _instance_name(stem: str) -> str:
    """A SPICE-safe instance name.

    The extractor names a device or a parasitic after the net it belongs to,
    and those names carry characters ngspice treats as syntax: ``$`` for an
    anonymous net, ``|`` where two labels were drawn on one net
    (``EN|RESETn``). Left alone, ngspice mis-parses the card into a
    different-arity element and fails with a confusing "unknown parameter".
    """
    return "".join(
        character if character.isalnum() or character == "_" else "_"
        for character in stem
    )


# ==========================================================================
# Building one cell's composite netlist
# ==========================================================================


def _format_engineering(value: float, unit: str) -> str:
    return f"{value:.6g}{unit}"


def build_cell(cell: str) -> tuple[str, dict]:
    """Return ``(composite netlist text, audit dict)`` for one cell."""
    spec = ref.CELLS[cell]
    check_every_golden_device_is_accounted_for(cell)
    extracted = parse_extracted(REPORTS_DIR / cell / "extracted-parasitics.spice")
    reference = parse_reference(CELLS_DIR / f"{cell}.reference.spice")

    pins = pin_correspondence(extracted, reference)
    mapping = solve_correspondence(extracted, reference, pins)
    verify_correspondence(extracted, reference, mapping)

    aliases = body_aliases(cell)
    cap_pairs = cap_plate_pairs(cell)

    # --- every drawn cap wired, exactly the "every golden device accounted
    # for" guarantee `check_every_golden_device_is_accounted_for` gives the
    # MOS half, extended to caps: a value the manifest never declared, or the
    # wrong DEVICE COUNT, must fail loudly rather than leave a cap floating
    # or silently under/over-count it.
    expected_caps = drawn_cap_unit_count(cell)
    if len(extracted.caps) != expected_caps:
        raise CompositeError(
            f"{cell}: extraction carries {len(extracted.caps)} drawn MiM cap(s), "
            f"the manifest declares {expected_caps}"
        )
    for name, _node_a, _node_b, value, _klass in extracted.caps:
        if round(value, 21) not in cap_pairs:
            raise CompositeError(
                f"{cell}: drawn cap {name!r} extracts at {value:.6g} F, which "
                "matches no golden cap's value -- cannot wire its plates"
            )

    def to_composite(net_extracted: str) -> str:
        net_reference = mapping[net_extracted]
        return composite_name(aliases.get(net_reference, net_reference))

    # --- the net namespace -------------------------------------------------
    # Two distinct extracted nets landing on one composite name would be a
    # short introduced by this script, which is the exact failure the issue
    # asks to rule out by NAME rather than by "it simulated". Exactly one
    # merge is legitimate and is listed device-by-device: the deck's synthetic
    # body nets (the substrate global, each anonymous Nwell) rejoining the
    # schematic node they are tied to.
    layout_nets: dict[str, list[str]] = {}
    for net_extracted in extracted.nets:
        if net_extracted in extracted.cap_nets:
            continue  # a drawn cap's plate net; wired by value, see cap_pairs
        name = to_composite(net_extracted)
        layout_nets.setdefault(name, []).append(net_extracted)
    for name, members in layout_nets.items():
        if len(members) == 1:
            continue
        offenders = [net for net in members if mapping[net] not in aliases]
        if len(offenders) > 1:
            raise CompositeError(
                f"{cell}: extracted nets {offenders!r} both map to composite "
                f"net {name!r} -- the splice would short them"
            )

    ports = ref.subckt_ports(
        (NETLIST_DIR / spec["source"]).read_text(), spec["subckt"]
    )

    # --- the spliced (ideal, schematic) devices ----------------------------
    spliced: list[tuple[str, list[str], str, str]] = []  # name, nodes, trailing, origin
    if "assembly" in spec:
        for inst, sub_cell, rename in ref.instance_renames(cell):
            sub_spec = ref.CELLS[sub_cell]
            drawn_caps = frozenset(sub_spec.get("caps", []))
            for name, nodes, trailing in _non_mos_cards(
                spec["source"], sub_spec["subckt"], drawn_caps
            ):
                spliced.append(
                    (
                        f"X{name[1:]}_{inst}",
                        [composite_name(rename(node)) for node in nodes],
                        trailing,
                        f"{inst} ({sub_cell})",
                    )
                )
    else:
        drawn_caps = frozenset(spec.get("caps", []))
        for name, nodes, trailing in _non_mos_cards(
            spec["source"], spec["subckt"], drawn_caps
        ):
            spliced.append((name, [composite_name(node) for node in nodes], trailing, cell))

    spliced_nets: dict[str, int] = {}
    for _name, nodes, _trailing, _origin in spliced:
        for node in nodes:
            spliced_nets[node] = spliced_nets.get(node, 0) + 1

    new_nets = sorted(net for net in spliced_nets if net not in layout_nets)
    for port in ports:
        if port not in layout_nets and port not in spliced_nets:
            raise CompositeError(
                f"{cell}: golden port {port!r} exists in neither the extraction "
                "nor the spliced devices"
            )

    # --- the parasitics coverage counters (klayout-tools#283 sanity check) --
    parasitic_r = {
        node_a: value
        for letter, _n, node_a, node_b, value in extracted.parasitics
        if letter == "R" and node_b == node_a + PARASITIC_SUFFIX
    }
    parasitic_c = {
        node_b[: -len(PARASITIC_SUFFIX)]: value
        for letter, _n, node_b, _n2, value in (
            (letter, n, a, b, v) for letter, n, a, b, v in extracted.parasitics
        )
        if letter == "C" and node_b.endswith(PARASITIC_SUFFIX)
    }

    mos_counts = extracted.mos_terminal_counts()

    # --- emit --------------------------------------------------------------
    text = _emit(
        cell=cell,
        spec=spec,
        ports=ports,
        extracted=extracted,
        to_composite=to_composite,
        spliced=spliced,
        new_nets=new_nets,
        cap_pairs=cap_pairs,
    )

    audit = _audit(
        cell=cell,
        extracted=extracted,
        reference=reference,
        mapping=mapping,
        pins=pins,
        aliases=aliases,
        layout_nets=layout_nets,
        spliced=spliced,
        spliced_nets=spliced_nets,
        new_nets=new_nets,
        parasitic_r=parasitic_r,
        parasitic_c=parasitic_c,
        mos_counts=mos_counts,
        ports=ports,
        cap_pairs=cap_pairs,
    )
    return text, audit


def _emit(cell, spec, ports, extracted, to_composite, spliced, new_nets, cap_pairs) -> str:
    lines = [
        f"* {cell} -- COMPOSITE post-layout netlist",
        "* generated by layout/composite_netlist.py -- do not edit.",
        "*",
        "* WHAT THIS IS",
        "*   MOS devices and interconnect parasitics taken from the LAYOUT",
        f"*     layout/reports/{cell}/extracted-parasitics.spice",
        "*     (klt extract --deck gf180mcu --parasitics), plus every non-MOS",
        "*     device taken VERBATIM from the golden schematic export",
        f"*     design/netlist/{spec['source']}.",
        "*",
        "* WHAT THIS IS NOT",
        "*   It is NOT a parasitic-extracted analog core. The vertical PNPs,",
        "*   poly resistors and MiM caps below are IDEAL SCHEMATIC DEVICES:",
        "*   they are not drawn in the layout at all, so they carry no",
        "*   extracted geometry, no parasitic R/C, and no layout-derived",
        "*   matching. Any claim recorded against this netlist must say so in",
        "*   the record's Claim field -- what it substantiates is real",
        "*   interconnect parasitics loading the real MOS topology, and",
        "*   nothing more. See layout/composite/AUDIT.md.",
        "*",
        "*   Device bodies are the other place this netlist takes connectivity",
        "*   from the schematic: the curated deck draws no tap or well-label",
        "*   layer, so an extracted body lands on a global substrate net or an",
        "*   anonymous well net. Those are restored to the schematic's own",
        "*   body nodes here, because a floating body cannot be simulated.",
        "*",
        f".subckt {cell} {' '.join(ports)}",
    ]

    lines.append("")
    lines.append("* ---- MOS devices: extracted from the layout ----")
    for device in extracted.devices:
        if device.comment:
            lines.append(device.comment)
        nodes = " ".join(to_composite(node) for node in device.nodes)
        model = f"{device.klass}_03v3"
        params = [
            f"L={_number(device.params['L']) * 1e6:.6g}u",
            f"W={_number(device.params['W']) * 1e6:.6g}u",
            "nf=1",
        ]
        for key, unit in (("AD", "p"), ("AS", "p"), ("PD", "u"), ("PS", "u")):
            if key in device.params:
                scale = 1e12 if unit == "p" else 1e6
                params.append(
                    f"{key.lower()}="
                    f"{_format_engineering(_number(device.params[key]) * scale, unit)}"
                )
        params.append("m=1")
        lines.append(
            f"XM_{_instance_name(device.name)} {nodes} {model} {' '.join(params)}"
        )

    if extracted.caps:
        lines.append("")
        lines.append("* ---- MiM cap devices: extracted from the layout ----")
        lines.append(
            "* Real drawn devices (klayout-tools#314/#315), not spliced from the"
        )
        lines.append(
            "* schematic. `klt` cannot route a capacitor plate onto a net (same"
        )
        lines.append(
            "* limitation `layout/lvs_reference.py` documents for the LVS"
        )
        lines.append(
            "* reference), so the extraction's own plate nodes are isolated --"
        )
        lines.append(
            "* leaving them that way would carry no capacitive loading on the"
        )
        lines.append(
            "* real net at all, so the two plates are wired to the schematic's"
        )
        lines.append(
            "* own nets instead, by value (composite_netlist.cap_plate_pairs;"
        )
        lines.append(
            "* a capacitor is non-polarized, so which plate is which is not"
        )
        lines.append(
            "* observable and does not matter electrically). Bare value, no"
        )
        lines.append(
            "* trailing model name: unlike the LVS reference (a device-CLASS"
        )
        lines.append(
            "* comparison klt's own SPICE reader needs), this is a netlist"
        )
        lines.append(
            "* ngspice simulates, and a trailing token after the value is a"
        )
        lines.append("* parameter ngspice expects to parse, not a class tag.")
        for name, _node_a, _node_b, value, klass in extracted.caps:
            # cap_plate_pairs already resolves to composite-space net names
            # (it runs the schematic's own node names through the same
            # rename()/composite_name() the MOS half uses) -- not through
            # `to_composite`, which maps an EXTRACTED net through the solved
            # correspondence and these plate nodes were never in it.
            net_a, net_b = cap_pairs[round(value, 21)]
            lines.append(f"* {klass}, m=1")
            lines.append(f"C_{_instance_name(name)} {net_a} {net_b} {value:.6g}")

    if extracted.parasitics:
        lines.append("")
        lines.append(
            "* ---- interconnect parasitics: extracted from the layout ----"
        )
        lines.append(
            "* One series R + one lumped C to substrate per net, from the deck's"
        )
        lines.append(
            "* curated sheet-resistance / capacitance table (klt extract"
        )
        lines.append("* --parasitics). First order, not a field solve.")
        for letter, name, node_a, node_b, value in extracted.parasitics:

            def render(node: str) -> str:
                if node.endswith(PARASITIC_SUFFIX):
                    base = node[: -len(PARASITIC_SUFFIX)]
                    return to_composite(base) + PARASITIC_SUFFIX
                return to_composite(node)

            lines.append(
                f"{letter}par_{_instance_name(name)} {render(node_a)} "
                f"{render(node_b)} {value:.6g}"
            )

    lines.append("")
    lines.append("* ---- non-MOS devices: IDEAL, verbatim from the schematic ----")
    if new_nets:
        lines.append(
            "* Nodes introduced by these devices alone (they exist in no"
        )
        lines.append(
            f"* extraction, so they carry no parasitics): {', '.join(new_nets)}"
        )
    for name, nodes, trailing, origin in spliced:
        lines.append(f"* from {origin}")
        lines.append(f"{name} {' '.join(nodes)} {trailing}")

    lines.append("")
    lines.append(f".ends {cell}")
    return "\n".join(lines) + "\n"


def _audit(
    cell,
    extracted,
    reference,
    mapping,
    pins,
    aliases,
    layout_nets,
    spliced,
    spliced_nets,
    new_nets,
    parasitic_r,
    parasitic_c,
    mos_counts,
    ports,
    cap_pairs,
) -> dict:
    nets: list[dict] = []
    for name, members in layout_nets.items():
        # ``members`` is every extracted net that lands on this composite
        # node: normally one, and more only where a synthetic body net
        # rejoined the schematic node it is tied to.
        resistances = [parasitic_r[net] for net in members if net in parasitic_r]
        capacitances = [parasitic_c[net] for net in members if net in parasitic_c]
        nets.append(
            {
                "net": name,
                "extracted_net": members[0] if len(members) == 1 else None,
                "extracted_nets": sorted(members),
                "reference_nets": sorted(mapping[net] for net in members),
                "body_nets_merged": sorted(
                    mapping[net] for net in members if mapping[net] in aliases
                ),
                "labelled_in_layout": any(not net.startswith("$") for net in members),
                "origin": "layout",
                "mos_terminals": sum(mos_counts.get(net, 0) for net in members),
                "spliced_terminals": spliced_nets.get(name, 0),
                "parasitic_r_ohm": round(sum(resistances), 4) if resistances else None,
                "parasitic_c_ff": round(sum(capacitances) * 1e15, 4)
                if capacitances
                else None,
                "is_pin": any(net in pins for net in members),
            }
        )
    for name in new_nets:
        nets.append(
            {
                "net": name,
                "extracted_net": None,
                "extracted_nets": [],
                "reference_nets": [],
                "body_nets_merged": [],
                "labelled_in_layout": False,
                "origin": "schematic",
                "mos_terminals": 0,
                "spliced_terminals": spliced_nets.get(name, 0),
                "parasitic_r_ohm": None,
                "parasitic_c_ff": None,
                "is_pin": False,
            }
        )
    nets.sort(key=lambda row: row["net"])

    # The klayout-tools#283 sanity check, on the extracted netlist's OWN net
    # namespace (not the composite one), cross-checked against what the
    # recorded klt extract JSON says about the same run: a silent zero, or a
    # quiet collapse in coverage, has to be visible rather than absorbed.
    report = json.loads(
        (REPORTS_DIR / cell / "extracted-parasitics.json").read_text()
    )
    reported = report.get("parasitics") or {}
    reported_nets = len(reported.get("nets", []))
    covered = {net for net in parasitic_c}
    if reported_nets != len(covered):
        raise CompositeError(
            f"{cell}: extracted-parasitics.json reports {reported_nets} nets with "
            f"parasitics, the netlist carries {len(covered)}"
        )
    if report.get("net_count") != len(extracted.nets):
        raise CompositeError(
            f"{cell}: extracted-parasitics.json reports {report.get('net_count')} "
            f"nets, the netlist carries {len(extracted.nets)}"
        )
    if reported_nets == 0:
        raise CompositeError(
            f"{cell}: 0 nets carry parasitics -- silent-zero regression "
            "(klayout-tools#283)"
        )

    audit = {
        "cell": cell,
        "note": CELLS[cell]["note"],
        "ports": list(ports),
        "counts": {
            "mos_devices_from_layout": len(extracted.devices),
            "mim_caps_from_layout": len(extracted.caps),
            "spliced_devices_from_schematic": len(spliced),
            "nets_total": len(nets),
            "nets_from_layout": len(layout_nets),
            "nets_schematic_only": len(new_nets),
            "reference_devices": len(reference.devices),
            "extracted_nets": len(extracted.nets),
        },
        "parasitics": {
            "nets_with_parasitics": reported_nets,
            "nets_in_extraction": len(extracted.nets),
            "coverage_pct": round(100.0 * reported_nets / len(extracted.nets), 2),
            "r_cards": sum(1 for p in extracted.parasitics if p[0] == "R"),
            "c_cards": sum(1 for p in extracted.parasitics if p[0] == "C"),
            "total_resistance_ohm": round(sum(parasitic_r.values()), 4),
            "total_capacitance_ff": round(sum(parasitic_c.values()) * 1e15, 4),
            "extracted_nets_without_parasitics": sorted(
                f"{net} -> {composite_name(aliases.get(mapping[net], mapping[net]))}"
                for net in extracted.nets
                if net not in parasitic_c and net not in extracted.cap_nets
            ),
        },
        "mim_caps_from_layout": [
            {
                "name": f"C_{_instance_name(name)}",
                "nodes": list(cap_pairs[round(value, 21)]),
                "value_f": value,
                "model": klass,
            }
            for name, _node_a, _node_b, value, klass in extracted.caps
        ],
        "spliced_devices": [
            {"name": name, "nodes": nodes, "model": trailing.split()[0], "origin": origin}
            for name, nodes, trailing, origin in spliced
        ],
        "schematic_only_nets": new_nets,
        "nets": nets,
        "readme_claims": _check_readme_claims(cell, nets),
    }
    return audit


def _check_readme_claims(cell: str, nets: list[dict]) -> list[dict]:
    """Re-derive layout/README.md's 'Consequences to carry forward' bullets."""
    by_name = {row["net"]: row for row in nets}
    results = []
    for claim in CELLS[cell]["readme"]:
        findings = []
        holds = True
        for net in claim["nets"]:
            row = by_name.get(net)
            if row is None:
                findings.append(f"{net}: absent from the composite netlist entirely")
                holds = False
                continue
            in_extraction = row["origin"] == "layout"
            if in_extraction != claim["extracted"]:
                findings.append(
                    f"{net}: {'in' if in_extraction else 'not in'} the extraction, "
                    f"claim says {'in' if claim['extracted'] else 'not in'}"
                )
                holds = False
                continue
            if "mos_terminals" in claim and row["mos_terminals"] != claim["mos_terminals"]:
                findings.append(
                    f"{net}: {row['mos_terminals']} MOS terminal(s), "
                    f"claim says {claim['mos_terminals']}"
                )
                holds = False
                continue
            if "labelled" in claim and row["labelled_in_layout"] != claim["labelled"]:
                findings.append(
                    f"{net}: labelled={row['labelled_in_layout']}, "
                    f"claim says labelled={claim['labelled']}"
                )
                holds = False
                continue
            detail = (
                f"{net}: extracted as {row['extracted_net']}"
                if in_extraction
                else f"{net}: schematic-only"
            )
            if in_extraction:
                detail += f", {row['mos_terminals']} MOS terminal(s)"
                detail += (
                    ", labelled" if row["labelled_in_layout"] else ", unlabelled"
                )
            findings.append(detail)
        results.append({"claim": claim["claim"], "holds": holds, "findings": findings})
    return results


# ==========================================================================
# klt extract --parasitics
# ==========================================================================


def run_extraction(cell: str) -> None:
    """Re-run ``klt extract --parasitics`` and record it as a new artifact.

    Deliberately writes ``extracted-parasitics.spice`` / ``.json`` rather than
    touching ``extracted.spice`` / ``extract.json``: ``run_checks.sh`` keeps
    those byte-stable as the DRC/LVS flow's own repeatability contract.
    """
    request = json.loads((CELLS_DIR / f"{cell}.lvs.json").read_text())
    out_dir = REPORTS_DIR / cell
    out_dir.mkdir(parents=True, exist_ok=True)
    command = [
        "klt",
        "extract",
        str((CELLS_DIR / f"{cell}.gds").relative_to(REPO_ROOT)),
        "--deck",
        DECK,
        "--top",
        cell,
        "--parasitics",
        "-o",
        str((out_dir / "extracted-parasitics.spice").relative_to(REPO_ROOT)),
        "--format",
        "json",
    ]
    if request["layout"].get("top_cell_pins", False):
        command.append("--top-cell-pins")
    print(f"    $ {' '.join(command)}")
    result = subprocess.run(
        command, cwd=REPO_ROOT, capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        raise CompositeError(
            f"{cell}: klt extract --parasitics exited {result.returncode}\n"
            f"{result.stdout}\n{result.stderr}"
        )
    report = json.loads(result.stdout)
    (out_dir / "extracted-parasitics.json").write_text(
        json.dumps(report, indent=2) + "\n"
    )
    parasitics = report.get("parasitics") or {}
    net_count = report.get("net_count", 0)
    covered = len(parasitics.get("nets", []))
    if covered == 0:
        # klayout-tools#283: parasitics silently reading zero on unlabelled
        # nets is a regression this repo hit before and must never eat again.
        raise CompositeError(
            f"{cell}: --parasitics produced 0 nets with parasitics out of "
            f"{net_count} -- silent-zero regression (klayout-tools#283)"
        )
    print(f"    parasitics on {covered}/{net_count} nets")


# ==========================================================================
# Rendering / CLI
# ==========================================================================

AUDIT_HEADER = """\
# Composite post-layout netlists — per-cell audit

**Generated by `layout/composite_netlist.py`. Do not edit.**
Regenerate with `python3 layout/composite_netlist.py`; `--check` fails if this
file is stale.

A *composite* netlist is the layout's own MOS devices and interconnect
parasitics (`klt extract --deck gf180mcu --parasitics`) with the block's
non-MOS devices — vertical PNPs, poly resistors, MiM caps — spliced back in
**verbatim from the golden schematic export**, because none of them is drawn
in any extracted cell (`layout/README.md` → "Known deck limits"). The
convention, and what a result taken on one of these may and may not claim, is
[`layout/README.md` → "Composite post-layout netlists"](../README.md#composite-post-layout-netlists).

**The passives and bipolars below are ideal.** They carry no extracted
geometry, no parasitic R/C and no layout-derived matching. Every `sim/` record
taken against a composite netlist must say so in its **Claim** field.

The tables are generated from the artifacts, not transcribed: each net's row
says whether it came from the layout or only from the schematic, how many MOS
terminals it carries, how many spliced-in (ideal) terminals it carries, and
what parasitic R/C the extractor hung on it.
"""


def render_audit(audits: list[dict]) -> str:
    lines = [AUDIT_HEADER, "## Summary", ""]
    lines.append(
        "| cell | MOS devices (layout) | spliced devices (schematic) | nets | "
        "layout nets | schematic-only nets | nets with parasitics | ΣR (Ω) | ΣC (fF) |"
    )
    lines.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for audit in audits:
        counts = audit["counts"]
        par = audit["parasitics"]
        lines.append(
            f"| `{audit['cell']}` | {counts['mos_devices_from_layout']} | "
            f"{counts['spliced_devices_from_schematic']} | {counts['nets_total']} | "
            f"{counts['nets_from_layout']} | {counts['nets_schematic_only']} | "
            f"{par['nets_with_parasitics']}/{par['nets_in_extraction']} "
            f"({par['coverage_pct']} %) | {par['total_resistance_ohm']:.0f} | "
            f"{par['total_capacitance_ff']:.1f} |"
        )
    lines += [
        "",
        "The *nets with parasitics* column is the "
        "[klayout-tools#283](https://github.com/2AMLogic/klayout-tools/issues/283)"
        " sanity check: that issue was a silent **zero** on unlabelled nets. A",
        "future regression to zero — or a coverage number that quietly collapses —",
        "is visible here rather than being absorbed as a slightly-optimistic",
        "simulation. `--extract` refuses to write an artifact whose coverage is 0.",
        "",
    ]

    for audit in audits:
        cell = audit["cell"]
        lines += [
            f"## `{cell}` — {audit['note']}",
            "",
            f"Ports: {', '.join(f'`{p}`' for p in audit['ports'])}",
            "",
            "### `layout/README.md`'s own consequences, re-derived",
            "",
            "| verdict | claim | as measured |",
            "| --- | --- | --- |",
        ]
        for claim in audit["readme_claims"]:
            verdict = "holds" if claim["holds"] else "**FAILS**"
            findings = "; ".join(claim["findings"])
            lines.append(f"| {verdict} | {claim['claim']} | {findings} |")
        lines += [
            "",
            "### Nets",
            "",
            "| net | origin | extracted as | MOS terms | ideal terms | R (Ω) | C (fF) |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for row in audit["nets"]:
            if row["extracted_nets"]:
                extracted_as = ", ".join(f"`{n}`" for n in row["extracted_nets"])
                if row["labelled_in_layout"]:
                    extracted_as += " (labelled)"
                if row["body_nets_merged"]:
                    extracted_as += (
                        " + body "
                        + ", ".join(f"`{n}`" for n in row["body_nets_merged"])
                    )
            else:
                extracted_as = "—"
            resistance = (
                f"{row['parasitic_r_ohm']:.1f}"
                if row["parasitic_r_ohm"] is not None
                else "—"
            )
            capacitance = (
                f"{row['parasitic_c_ff']:.2f}"
                if row["parasitic_c_ff"] is not None
                else "—"
            )
            origin = (
                "layout (MOS + parasitics)"
                if row["origin"] == "layout"
                else "**schematic only (ideal)**"
            )
            lines.append(
                f"| `{row['net']}`{' *(pin)*' if row['is_pin'] else ''} | {origin} | "
                f"{extracted_as} | {row['mos_terminals']} | "
                f"{row['spliced_terminals']} | {resistance} | {capacitance} |"
            )
        lines += [
            "",
            "### Spliced-in (ideal) devices",
            "",
            "| device | model | nodes | from |",
            "| --- | --- | --- | --- |",
        ]
        for device in audit["spliced_devices"]:
            nodes = ", ".join(f"`{n}`" for n in device["nodes"])
            lines.append(
                f"| `{device['name']}` | `{device['model']}` | {nodes} | "
                f"{device['origin']} |"
            )
        lines.append("")
    return "\n".join(lines)


def generate(cells: list[str]) -> tuple[dict[Path, str], list[dict]]:
    outputs: dict[Path, str] = {}
    audits: list[dict] = []
    for cell in cells:
        text, audit = build_cell(cell)
        outputs[COMPOSITE_DIR / f"{cell}.composite.spice"] = text
        outputs[COMPOSITE_DIR / f"{cell}.audit.json"] = (
            json.dumps(audit, indent=2) + "\n"
        )
        audits.append(audit)
    return outputs, audits


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cell", help="operate on one cell only")
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate in memory and fail if a committed output differs",
    )
    parser.add_argument(
        "--extract",
        action="store_true",
        help="re-run 'klt extract --parasitics' first (needs klt on PATH)",
    )
    args = parser.parse_args(argv)

    cells = [args.cell] if args.cell else list(CELLS)
    unknown = [cell for cell in cells if cell not in CELLS]
    if unknown:
        print(f"unknown cell(s): {', '.join(unknown)}", file=sys.stderr)
        return 2

    try:
        if args.extract:
            for cell in cells:
                print(f"==> {cell}")
                run_extraction(cell)
        outputs, audits = generate(cells)
        if not args.cell:
            outputs[COMPOSITE_DIR / "AUDIT.md"] = render_audit(audits)
    except CompositeError as error:
        print(f"composite_netlist: {error}", file=sys.stderr)
        return 1

    failures = []
    for path, text in sorted(outputs.items()):
        rel = path.relative_to(REPO_ROOT)
        if args.check:
            if not path.is_file():
                failures.append(f"{rel}: not committed (run without --check)")
            elif path.read_text() != text:
                failures.append(f"{rel}: stale")
            else:
                print(f"ok {rel}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {rel}")

    for line in failures:
        print(f"FAIL {line}", file=sys.stderr)

    broken = [
        (audit["cell"], claim)
        for audit in audits
        for claim in audit["readme_claims"]
        if not claim["holds"]
    ]
    for cell, claim in broken:
        print(
            f"FAIL {cell}: layout/README.md claim does not hold -- "
            f"{claim['claim']} ({'; '.join(claim['findings'])})",
            file=sys.stderr,
        )

    return 1 if failures or broken else 0


if __name__ == "__main__":
    sys.exit(main())
