#!/usr/bin/env python3
"""Smoke-simulate every composite post-layout netlist at ``tt_27c_3.30v``.

    python3 layout/composite_smoke.py            # run all five, rewrite the reports
    python3 layout/composite_smoke.py --cell bias_core
    python3 layout/composite_smoke.py --check    # verify the committed reports are current

Needs ``ngspice`` and the gf180mcu PDK (resolved through ``sim/harness/pdk.py``,
so this uses exactly the PDK the corner runner uses). Everything else in
``layout/`` runs without them.

**This is plumbing proof, not evidence.** It answers one question -- *does the
composite netlist that ``layout/composite_netlist.py`` generates actually
elaborate, converge, and settle somewhere physical?* -- so that the follow-on
post-layout re-run issues are debugging physics, not netlist plumbing. It is
deliberately **not** a ``sim/`` record:

* one nominal PVT point, not the mandated matrix, so it cannot substantiate
  anything (``sim/README.md``: every recorded result carries the full PVT
  matrix);
* its bounds are loose sanity windows -- "a rail is a rail, a diode drop is a
  diode drop" -- not ratified spec limits, and they are not a substitute for
  the per-cell designer-check experiments under ``sim/``;
* the netlist under it has **ideal** passives and bipolars (see
  ``layout/composite/AUDIT.md``), so a real claim taken on it would have to
  say so in its Claim field anyway.

A real post-layout evidence record is a ``sim/<slug>/`` experiment run through
``sim/run_corners.py``, with ``Netlist provenance: composite post-layout``.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

LAYOUT_DIR = Path(__file__).resolve().parent
REPO_ROOT = LAYOUT_DIR.parent
COMPOSITE_DIR = LAYOUT_DIR / "composite"
REPORTS_DIR = LAYOUT_DIR / "reports"

sys.path.insert(0, str(LAYOUT_DIR))
sys.path.insert(0, str(REPO_ROOT / "sim"))

import composite_netlist  # noqa: E402
from harness import corners as harness_corners  # noqa: E402
from harness import pdk as harness_pdk  # noqa: E402

#: The one PVT point. ``tt_27c_3.30v`` is the ratified nominal corner-id
#: (sim/README.md); the section bundle comes from the harness's own table, so
#: a corner definition cannot drift between this and a recorded run.
CORNER = harness_corners.CORNERS["tt"]
TEMP_C = 27.0
VDD = 3.30
CORNER_ID = f"{CORNER.name}_{TEMP_C:g}c_{VDD:.2f}v"

_MEASURE_PREFIX = "m_"


class SmokeError(Exception):
    pass


#: The two netlists every cell is run against. The composite is the thing
#: under test; the golden schematic export is the CONTROL, run through a
#: byte-identical deck. That is what makes the numbers mean anything: a
#: composite netlist that elaborates and converges but has the splice on the
#: wrong node would still produce numbers, and only the side-by-side says
#: whether it produced the *same circuit*.
VARIANTS = ("composite", "schematic")


def netlist_path(cell: str, variant: str) -> Path:
    if variant == "composite":
        return COMPOSITE_DIR / f"{cell}.composite.spice"
    return REPO_ROOT / "design" / "netlist" / f"{cell}.spice"


def compose_deck(cell: str, pdk, variant: str = "composite") -> str:
    smoke = composite_netlist.CELLS[cell]["smoke"]
    lines = [
        f"* {cell} {variant}-netlist smoke deck @ {CORNER_ID}",
        "* GENERATED by layout/composite_smoke.py -- do not edit.",
        "",
        f'.include "{pdk.design_include}"',
    ]
    for section in CORNER.sections:
        lines.append(f'.lib "{pdk.model_lib}" {section}')
    lines += [
        "",
        f".temp {TEMP_C}",
        ".options reltol=1e-5 abstol=1e-15 vntol=1e-9",
        "",
        f'.include "{netlist_path(cell, variant)}"',
        "",
    ]
    lines += [line.format(vdd=VDD) for line in smoke["stimulus"]]
    lines += ["", ".control", "set numdgt=10", "set noaskquit"]
    lines += [f"  {analysis}" for analysis in smoke.get("analyses", ["op"])]
    for name, expr in smoke["measure"].items():
        lines.append(f"  let {_MEASURE_PREFIX}{name} = {expr}")
    for name in smoke["measure"]:
        lines.append(f"  print {_MEASURE_PREFIX}{name}")
    lines += [".endc", ".end", ""]
    return "\n".join(lines)


def parse_prints(text: str, names) -> dict[str, float]:
    found: dict[str, float] = {}
    for line in text.splitlines():
        fields = line.replace("=", " ").split()
        if len(fields) < 2:
            continue
        key = fields[0]
        if not key.startswith(_MEASURE_PREFIX):
            continue
        name = key[len(_MEASURE_PREFIX) :]
        if name not in names:
            continue
        try:
            found[name] = float(fields[-1])
        except ValueError:
            continue
    return found


def _simulate(cell: str, pdk, variant: str) -> tuple[dict[str, float], list[str]]:
    smoke = composite_netlist.CELLS[cell]["smoke"]
    deck = compose_deck(cell, pdk, variant)
    with tempfile.TemporaryDirectory() as work:
        deck_path = Path(work) / f"{cell}.{variant}.spice"
        deck_path.write_text(deck)
        result = subprocess.run(
            ["ngspice", "-b", str(deck_path)],
            capture_output=True,
            text=True,
            check=False,
            cwd=work,
        )
    log = result.stdout + result.stderr
    measurements = parse_prints(log, set(smoke["measure"]))

    problems: list[str] = []
    lowered = log.lower()
    for marker in ("singular matrix", "no convergence", "doanalyses: iteration"):
        if marker in lowered:
            problems.append(f"{variant}: ngspice reported {marker!r}")
    if result.returncode != 0:
        problems.append(f"{variant}: ngspice exited {result.returncode}")
    missing = sorted(set(smoke["measure"]) - set(measurements))
    if missing:
        problems.append(f"{variant}: no value printed for {', '.join(missing)}")
    return measurements, problems


def run_cell(cell: str, pdk) -> dict:
    smoke = composite_netlist.CELLS[cell]["smoke"]
    values: dict[str, dict[str, float]] = {}
    problems: list[str] = []
    for variant in VARIANTS:
        measurements, issues = _simulate(cell, pdk, variant)
        values[variant] = measurements
        problems.extend(issues)

    checks = []
    for name, (low, high) in smoke["sane"].items():
        value = values["composite"].get(name)
        control = values["schematic"].get(name)
        ok = value is not None and low <= value <= high
        control_ok = control is not None and low <= control <= high
        delta_pct = None
        if value is not None and control not in (None, 0.0):
            delta_pct = round((value - control) / abs(control) * 100.0, 3)
        checks.append(
            {
                "measurement": name,
                "composite": value,
                "schematic_control": control,
                "delta_pct": delta_pct,
                "min": low,
                "max": high,
                "pass": ok,
                "control_pass": control_ok,
            }
        )
        if not ok:
            problems.append(
                f"composite {name} = {value} outside the sanity window "
                f"[{low}, {high}]"
            )
        if not control_ok:
            # The control failing means the WINDOW is wrong, not the bridge --
            # say which, rather than blaming the composite netlist for a bound
            # the schematic never met either.
            problems.append(
                f"schematic control {name} = {control} is itself outside "
                f"[{low}, {high}] -- the sanity window is wrong, not the splice"
            )

    return {
        "cell": cell,
        "purpose": "composite-netlist plumbing proof -- NOT a sim/ evidence record; "
        "one nominal PVT point, loose sanity windows, ideal passives/bipolars "
        "(see layout/composite/AUDIT.md)",
        "netlist": f"layout/composite/{cell}.composite.spice",
        "control_netlist": f"design/netlist/{cell}.spice",
        "corner_id": CORNER_ID,
        "corner_sections": list(CORNER.sections),
        "temp_c": TEMP_C,
        "vdd_v": VDD,
        "analyses": list(smoke.get("analyses", ["op"])),
        "converged": not problems,
        "measurements": {
            name: round(value, 9)
            for name, value in sorted(values["composite"].items())
        },
        "schematic_control_measurements": {
            name: round(value, 9)
            for name, value in sorted(values["schematic"].items())
        },
        "sanity_checks": checks,
        "problems": problems,
    }


def render(results: list[dict]) -> str:
    lines = [
        "# Composite post-layout netlists — DC operating-point smoke run",
        "",
        "**Generated by `layout/composite_smoke.py`. Do not edit.**",
        "",
        "One nominal point (`" + CORNER_ID + "`) per composite netlist.",
        "This is **plumbing proof, not evidence**: it shows the",
        "generated netlist elaborates, converges, and settles somewhere",
        "physical, so that the post-layout re-run issues are not debugging the",
        "netlist bridge and the physics at the same time. It substantiates no",
        "spec row — the PVT matrix `sim/README.md` mandates is absent by",
        "design, the windows below are loose sanity bounds rather than ratified",
        "limits, and the passives and bipolars in the netlist are ideal",
        "(`layout/composite/AUDIT.md`).",
        "",
        "Each cell is run **twice through a byte-identical deck**: once on its",
        "composite netlist and once on `design/netlist/<cell>.spice` as a",
        "control. A netlist whose splice landed on the wrong node would still",
        "converge and still print numbers; only the side-by-side says whether",
        "it is the same circuit. The `Δ` column is the composite's departure",
        "from the schematic — which, on a netlist whose only added physics is",
        "interconnect R/C, is what the parasitics are worth on that node.",
        "",
        "**Expect Δ ≈ 0 on every operating point, and that is not a null",
        "result — it is a property of the parasitic model.** `klt extract",
        "--parasitics` emits one series R into one lumped C per net; the R",
        "carries no DC current (its only load is that C) and the C is a DC",
        "open, so every DC quantity here is parasitic-invariant *by",
        "construction*. What a Δ ≈ 0 does prove is that the splice landed on",
        "the right nodes: `VREF`, the sense taps, `PTAT`/`CTAT` and the",
        "supply current all reproduce the schematic exactly, which a",
        "mis-attached divider or PNP array could not do. The one measurement",
        "below that the parasitics *can* move is `temp_por_top`'s",
        "`t_release_ms` — a switching edge, where the extracted interconnect",
        "capacitance is real load. Post-layout claims taken on these netlists",
        "should therefore be timing/edge claims, not DC ones.",
        "",
        "| cell | analysis | converged | Δ vs schematic control |",
        "| --- | --- | --- | --- |",
    ]
    for result in results:
        deltas = ", ".join(
            f"`{check['measurement']}` {check['delta_pct']:+.2f} %"
            for check in result["sanity_checks"]
            if check["delta_pct"] is not None
        )
        lines.append(
            f"| `{result['cell']}` | `{result['analyses'][0]}` | "
            f"{'yes' if result['converged'] else '**NO**'} | {deltas} |"
        )
    lines += [
        "",
        "## Operating points and sanity windows",
        "",
        "| cell | measurement | composite | schematic control | Δ | window | verdict |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for result in results:
        for check in result["sanity_checks"]:
            value = "—" if check["composite"] is None else f"{check['composite']:.6g}"
            control = (
                "—"
                if check["schematic_control"] is None
                else f"{check['schematic_control']:.6g}"
            )
            delta = "—" if check["delta_pct"] is None else f"{check['delta_pct']:+.2f} %"
            lines.append(
                f"| `{result['cell']}` | `{check['measurement']}` | {value} | "
                f"{control} | {delta} | [{check['min']}, {check['max']}] | "
                f"{'pass' if check['pass'] else '**FAIL**'} |"
            )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cell", help="run one cell only")
    parser.add_argument(
        "--check",
        action="store_true",
        help="re-run and fail if a committed report differs",
    )
    args = parser.parse_args(argv)

    cells = [args.cell] if args.cell else list(composite_netlist.CELLS)
    unknown = [cell for cell in cells if cell not in composite_netlist.CELLS]
    if unknown:
        print(f"unknown cell(s): {', '.join(unknown)}", file=sys.stderr)
        return 2

    try:
        pdk = harness_pdk.find_pdk()
    except harness_pdk.PdkNotFound as error:
        print(error, file=sys.stderr)
        return 3

    results = []
    for cell in cells:
        print(f"==> {cell} @ {CORNER_ID}")
        result = run_cell(cell, pdk)
        results.append(result)
        for problem in result["problems"]:
            print(f"    ! {problem}")
        for name, value in result["measurements"].items():
            print(f"    {name} = {value:.6g}")

    outputs: dict[Path, str] = {}
    for result in results:
        outputs[REPORTS_DIR / result["cell"] / "composite-smoke.json"] = (
            json.dumps(result, indent=2) + "\n"
        )
    if not args.cell:
        outputs[COMPOSITE_DIR / "SMOKE.md"] = render(results)

    failures = []
    for path, text in sorted(outputs.items()):
        rel = path.relative_to(REPO_ROOT)
        if args.check:
            if not path.is_file():
                failures.append(f"{rel}: not committed")
            elif path.read_text() != text:
                failures.append(f"{rel}: differs from this run")
            else:
                print(f"ok {rel}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {rel}")

    for line in failures:
        print(f"FAIL {line}", file=sys.stderr)
    unconverged = [r["cell"] for r in results if not r["converged"]]
    for cell in unconverged:
        print(f"FAIL {cell}: composite netlist did not smoke-test clean", file=sys.stderr)
    return 1 if failures or unconverged else 0


if __name__ == "__main__":
    sys.exit(main())
