#!/usr/bin/env python3
"""CDG-resize tradeoff for sim/por-output-chain-deglitch/ (issue #182).

    python3 sim/por-output-chain-deglitch/control/run_cdg_tradeoff.py

`design/por_output_chain.md`'s "Deglitch dwell -- `CDG` is bounded on *both*
sides" says the dwell capacitor "is not free to grow", and issue #182 asks
whether it has to anyway, now that the post-layout falling dwell has eroded.
This deck answers that with a measurement instead of an argument: it walks
`XCDG`'s drawn MiM dimensions on the **post-layout** netlist and, at each
size, measures both bounds.

    ceiling   `dwell_pgdg_halfib_us` at `ss_-40c_2.97v` -- the corner
              `spec/target-spec.md#por-brownout`'s <= 10 us `T_dip,min` check
              binds at (8.03 us as drawn, post-layout).
    floor     the glitch width at which the filter stops rejecting, at the two
              fast corners -- the bound the historical `CDG` = 98 fF failure
              hit, measured directly by `run_glitch_width_sweep.py`'s method.

**This is a what-if on the extracted netlist, not a proposed layout.** A real
`CDG` resize means redrawing the MiM, re-extracting, and re-running every
post-layout record; a bigger drawn capacitor would also carry more
interconnect of its own. So the floor these numbers show is *optimistic* for
a given size, and the ceiling is *optimistic* too -- which only strengthens a
conclusion of the form "even the optimistic version does not buy enough".

Writes:

    decks/cdg_<size>__<point>__<width>.spice   the exact deck as run
    decks/dut_cdg_<size>.spice                 the DUT netlist it includes
    logs/cdg_<size>__<point>__<width>.log      raw ngspice output, verbatim
    cdg_results.md                             the tradeoff table

Control experiment, not a record -- overwritten in place on every run (see
``sim/README.md``, "Control experiments").

Stdlib only, no virtualenv required.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

CONTROL_DIR = Path(__file__).resolve().parent
EXPERIMENT_DIR = CONTROL_DIR.parent
REPO_ROOT = CONTROL_DIR.parents[2]

sys.path.insert(0, str(REPO_ROOT / "sim"))

from harness import HARNESS_VERSION, corners as corners_mod, runner  # noqa: E402
from harness.pdk import PdkNotFound, find_pdk  # noqa: E402

FRAGMENT = CONTROL_DIR / "cdg_tradeoff.spice"
POSTLAYOUT_NETLIST = REPO_ROOT / "layout" / "postlayout" / "por_output_chain.spice"
MANIFEST = EXPERIMENT_DIR / "testbench" / "tb.json"

STOP_S = 1.10e-3
TSTEP_S = 20e-9
EDGE_S = 0.1e-6
DIP_START_S = 1000.0e-6

MIM_FF_PER_UM2 = 2.0  # cap_mim_2f0_*: 2.0 fF/um^2

# XCDG's drawn side length, in um. 11 um is what design/por_output_chain.sch
# draws today (121 um^2 -> 242 fF).
SIZES_UM = [11.0, 12.0, 13.0, 14.0]

# Ceiling family: one long dip, measured on the half-IBIAS DUT.
CEILING_DIP_US = 30.0
CEILING_POINTS: list[tuple[str, str, float, float]] = [
    ("ss_-40c_2.97v", "ss", -40.0, 2.97),
]

# Floor family: glitch widths at the two fast corners.
FLOOR_WIDTHS_US = [1.0, 1.25, 1.5, 1.75, 2.0, 2.25]
FLOOR_POINTS: list[tuple[str, str, float, float]] = [
    ("ff_125c_2.97v", "ff", 125.0, 2.97),
    ("ff_125c_3.63v", "ff", 125.0, 3.63),
]

_CDG_RE = re.compile(r"^(X\d+\s+NDG\s+VSS\s+cap_mim\S*\s+)c_width=\S+\s+c_length=\S+(.*)$", re.M)


def size_slug(size_um: float) -> str:
    return f"{size_um:g}u".replace(".", "p")


def dut_netlist(size_um: float) -> str:
    text = POSTLAYOUT_NETLIST.read_text()
    matches = _CDG_RE.findall(text)
    if len(matches) != 1:
        raise SystemExit(
            f"expected exactly one 'NDG VSS cap_mim...' line in {POSTLAYOUT_NETLIST},"
            f" found {len(matches)}"
        )
    return _CDG_RE.sub(rf"\g<1>c_width={size_um:g}u c_length={size_um:g}u\g<2>", text)


def compose_deck(
    pdk,
    size_um: float,
    corner_name: str,
    temp_c: float,
    vdd: float,
    width_us: float,
    options: list[str],
    deck_dir: Path,
) -> str:
    corner = corners_mod.CORNERS[corner_name]
    fragment_rel = os.path.relpath(FRAGMENT, deck_dir)
    width_s = width_us * 1e-6
    t_lo = DIP_START_S - EDGE_S
    t_hi = DIP_START_S
    t_end = DIP_START_S + width_s
    t_up = t_end + EDGE_S
    lines = [
        f"* por-output-chain-deglitch CDG tradeoff -- XCDG {size_um:g}u x {size_um:g}u"
        f" @ {corner_name} / {temp_c:g} C / {vdd:g} V, {width_us:g} us dip"
        " -- GENERATED by run_cdg_tradeoff.py, do not edit",
        f"* pdk={pdk.variant}@{pdk.version}",
        "",
        f".param vdd_val={vdd!r}",
        f".param t_dip_lo={t_lo!r}",
        f".param t_dip_hi={t_hi!r}",
        f".param t_dip_end={t_end!r}",
        f".param t_dip_up={t_up!r}",
        f".param stop_s={STOP_S!r}",
        "",
    ]
    lines += runner.deck_preamble(pdk, corner, temp_c, options)
    lines += [
        "",
        f'.include "{fragment_rel}"',
        f'.include "dut_cdg_{size_slug(size_um)}.spice"',
        "",
        f".tran {TSTEP_S!r} {{stop_s}}",
        "",
        f".meas tran timbefore find v(xdut1.tim) at={DIP_START_S - 1e-6!r}",
        f".meas tran pgdgmin min v(xdut1.pgdg) from={t_lo!r} to={t_end + 40e-6!r}",
        f".meas tran timafter min v(xdut1.tim) from={t_lo!r} to={t_end + 40e-6!r}",
        f".meas tran tpgf1 when v(xdut1.pgdg)=1.0 fall=1 td={t_lo!r}",
        f".meas tran tpgf2 when v(xdut2.pgdg)=1.0 fall=1 td={t_lo!r}",
        "",
        ".end",
        "",
    ]
    return "\n".join(lines)


def verdict(meas: dict[str, float]) -> str:
    """Same functional criterion as run_glitch_width_sweep.py: TIM is the
    read-out, because a glitch that reaches PGDG fires XMDIS and discharges the
    one-shot. TIM only ever *rises* while the filter is rejecting, so any
    material fall is a disturbance."""
    lost = (meas["timbefore"] - meas["timafter"]) / meas["timbefore"]
    if lost > 0.5:
        return "**through**"
    if lost > 0.01:
        return "partial"
    return "rejected"


def main() -> int:
    try:
        pdk = find_pdk()
        ngspice_version = runner.ngspice_version()
    except (PdkNotFound, runner.NgspiceMissing) as exc:
        print(exc, file=sys.stderr)
        return 3

    options = list(json.loads(MANIFEST.read_text()).get("options", []))
    deck_dir = CONTROL_DIR / "decks"
    log_dir = CONTROL_DIR / "logs"
    for d in (deck_dir, log_dir):
        d.mkdir(exist_ok=True)

    for size_um in SIZES_UM:
        (deck_dir / f"dut_cdg_{size_slug(size_um)}.spice").write_text(dut_netlist(size_um))

    ceiling: dict[tuple[float, str], dict[str, float]] = {}
    floor: dict[tuple[float, str, float], dict[str, float]] = {}

    def run(size_um, point_id, corner_name, temp_c, vdd, width_us, required):
        run_id = f"cdg_{size_slug(size_um)}__{point_id}__{width_us:g}us"
        deck_path = deck_dir / f"{run_id}.spice"
        deck_path.write_text(
            compose_deck(pdk, size_um, corner_name, temp_c, vdd, width_us, options, deck_dir)
        )
        proc = subprocess.run(
            ["ngspice", "-b", deck_path.name],
            capture_output=True,
            text=True,
            cwd=deck_dir,
            check=False,
            timeout=1800,
        )
        output = proc.stdout + "\n" + proc.stderr
        (log_dir / f"{run_id}.log").write_text(output)
        meas = runner.parse_bare_measurements(output)
        missing = [k for k in required if k not in meas]
        if missing:
            print(f"{run_id}: missing measurements {missing}", file=sys.stderr)
            print(output[-3000:], file=sys.stderr)
            raise SystemExit(2)
        return run_id, meas

    for size_um in SIZES_UM:
        for point_id, corner_name, temp_c, vdd in CEILING_POINTS:
            run_id, meas = run(
                size_um, point_id, corner_name, temp_c, vdd, CEILING_DIP_US, ("tpgf1", "tpgf2")
            )
            ceiling[(size_um, point_id)] = {
                "dwell_1x_us": (meas["tpgf1"] - DIP_START_S) * 1e6,
                "dwell_halfib_us": (meas["tpgf2"] - DIP_START_S) * 1e6,
            }
            print(
                f"{run_id}: dwell 1x {ceiling[(size_um, point_id)]['dwell_1x_us']:.3f} us,"
                f" halfIB {ceiling[(size_um, point_id)]['dwell_halfib_us']:.3f} us"
            )
        for point_id, corner_name, temp_c, vdd in FLOOR_POINTS:
            for width_us in FLOOR_WIDTHS_US:
                run_id, meas = run(
                    size_um,
                    point_id,
                    corner_name,
                    temp_c,
                    vdd,
                    width_us,
                    ("timbefore", "timafter", "pgdgmin"),
                )
                floor[(size_um, point_id, width_us)] = meas
                print(f"{run_id}: {verdict(meas)} (PGDG min {meas['pgdgmin']:.4f} V)")

    write_results(ceiling, floor, pdk, ngspice_version)
    print(f"wrote {(CONTROL_DIR / 'cdg_results.md').relative_to(REPO_ROOT)}")
    return 0


def write_results(ceiling: dict, floor: dict, pdk, ngspice_version: str) -> None:
    lines: list[str] = [
        "# por-output-chain-deglitch CDG-resize tradeoff -- generated, do not edit",
        "",
        "Generated by `sim/por-output-chain-deglitch/control/run_cdg_tradeoff.py`"
        " (issue #182). Re-run it to regenerate this file, the decks under `decks/`"
        " and the raw ngspice logs under `logs/`. The numbers quoted in"
        " `design/por_output_chain.md` are transcribed from here, and from nowhere"
        " else.",
        "",
        "**A what-if on the extracted netlist, not a proposed layout.** `XCDG`'s"
        " drawn MiM dimensions are rewritten in a copy of"
        " `layout/postlayout/por_output_chain.spice`; the surrounding interconnect"
        " parasitics are left at the values extracted for the 11 um x 11 um"
        " capacitor that is actually drawn. A real resize would redraw the MiM,"
        " carry more interconnect of its own, and require re-extraction -- so both"
        " bounds below are *optimistic* for a given size.",
        "",
        "This is a **control experiment, not a record** -- overwritten in place on"
        " every run (`sim/README.md`, \"Control experiments\").",
        "",
        f"- ngspice: `{ngspice_version}`",
        f"- PDK: `{pdk.variant}@{pdk.version}` ({pdk.source})",
        f"- harness: `{HARNESS_VERSION}`",
        "",
        "## Ceiling: `dwell_pgdg_halfib_us` vs. the ratified 10 us `T_dip,min`",
        "",
        "| `XCDG` | drawn area | `CDG` | corner | dwell, nominal `IBIAS` | dwell, half `IBIAS` | vs. 10 us |",
        "| --- | ---: | ---: | --- | ---: | ---: | --- |",
    ]
    for size_um in SIZES_UM:
        for point_id, _, _, _ in CEILING_POINTS:
            c = ceiling[(size_um, point_id)]
            area = size_um * size_um
            headroom = (10.0 - c["dwell_halfib_us"]) / 10.0 * 100.0
            drawn = " (as drawn)" if size_um == 11.0 else ""
            lines.append(
                f"| {size_um:g} um x {size_um:g} um{drawn} | {area:.0f} um^2 |"
                f" {area * MIM_FF_PER_UM2:.0f} fF | `{point_id}` |"
                f" {c['dwell_1x_us']:.3f} us | **{c['dwell_halfib_us']:.3f} us** |"
                f" {headroom:+.1f} % headroom |"
            )
    lines += [
        "",
        "## Floor: the glitch width the filter stops rejecting",
        "",
        "`rejected` = the one-shot's `TIM` keeps its charge; `partial` = `TIM` lost"
        " 1-50 % of it; `**through**` = `TIM` lost more than half, i.e. `XMDIS`"
        " fired and the reset pulse restarted.",
        "",
    ]
    for point_id, _, _, _ in FLOOR_POINTS:
        lines += [
            f"### `{point_id}`",
            "",
            "| `XCDG` | " + " | ".join(f"{w:g} us" for w in FLOOR_WIDTHS_US) + " |",
            "| --- | " + " | ".join("---" for _ in FLOOR_WIDTHS_US) + " |",
        ]
        for size_um in SIZES_UM:
            cells = [verdict(floor[(size_um, point_id, w)]) for w in FLOOR_WIDTHS_US]
            drawn = " (as drawn)" if size_um == 11.0 else ""
            lines.append(f"| {size_um:g} um{drawn} | " + " | ".join(cells) + " |")
        lines.append("")

    (CONTROL_DIR / "cdg_results.md").write_text("\n".join(lines))


if __name__ == "__main__":
    raise SystemExit(main())
