#!/usr/bin/env python3
"""Map the shape of the non-monotonic SS/-40 C transition band (#74).

    python3 sim/por-brownout-slew/analyze_transition_band.py

``analyze_boundary.py`` answers "where is the bound?" and reduces every
corner to a two-number bracket (fastest PASS, slowest FAIL). That reduction
is exactly what hides the finding #74 exists to characterize: between
roughly 3.40 and 4.2 mV/us the `ss`/-40 C family's PASS/FAIL verdicts are
**not monotonic** in slew, so a bracket is not a faithful summary of them.

This script therefore prints the ladder verdicts in full -- one PASS/FAIL
symbol per tested rung, per corner -- and pairs them with the event-timing
measurements from ``control/`` that say WHICH of the two failure modes each
FAIL is. It is a **derived** record per ``sim/README.md``: it runs no
simulation, makes no measurement of its own, cites its sources, and
supersedes nothing.

TWO SOURCES, TWO ROLES, KEPT SEPARATE:

  - ``records/*.md`` -- the full-81-point grid rungs. Everything in the
    Ladder-map and Band-extent sections is recombined from their own
    ``pass/fail`` columns, exactly as ``analyze_boundary.py`` does.
  - ``control/results.json`` -- the one-corner-family event-timing control,
    generated by ``control/run_band_mechanism.py`` from its own logs. A
    control is not corner evidence and substantiates no spec row
    (``sim/README.md``); it is read here only to attribute the mechanism
    behind verdicts the grid records establish on their own. Its numbers are
    READ from that file rather than transcribed, so each has exactly one
    source.

WHAT THIS SCRIPT DELIBERATELY DOES NOT DO: it does not re-derive, restate or
propose a value for ``dVDD/dt|fall,max``. That bound is ratified at
3.40 mV/us (``spec/target-spec.md#por-brownout`` clause (c), via #60), and
DR-011's rule that it must sit on the safe side of the ENTIRE transition
band is precisely what makes "some rung above it passed 81/81" not an
argument for moving it. #74 characterizes the band; it does not touch the
bound.
"""

from __future__ import annotations

import json
from pathlib import Path

from _rung_record import Rung, is_source_record, parse_record

EXPERIMENT_DIR = Path(__file__).resolve().parent
RECORDS_DIR = EXPERIMENT_DIR / "records"
CONTROL_JSON = EXPERIMENT_DIR / "control" / "results.json"


def load_rungs() -> list[Rung]:
    paths = sorted(p for p in RECORDS_DIR.glob("*.md") if is_source_record(p))
    if not paths:
        raise SystemExit(f"no records found under {RECORDS_DIR}")
    rungs = [parse_record(p) for p in paths]
    rungs.sort(key=lambda r: r.slew_mvus)
    return rungs


def load_control() -> dict | None:
    if not CONTROL_JSON.exists():
        return None
    return json.loads(CONTROL_JSON.read_text())


def us_after_dip(meas: dict, key: str, t_dip_s: float):
    t = meas.get(key)
    return None if t is None else (t - t_dip_s) * 1e6


def main() -> int:
    rungs = load_rungs()
    ctl = load_control()

    corner_ids = sorted(rungs[0].status)
    for r in rungs[1:]:
        if sorted(r.status) != corner_ids:
            raise ValueError(
                f"{r.record_id}: corner set does not match {rungs[0].record_id}"
            )

    latest_chrono_id = max(r.record_id for r in rungs)
    out_id = f"{latest_chrono_id}-transition-band"
    out_path = RECORDS_DIR / f"{out_id}.md"

    # A corner is "non-monotonic in the tested ladder" if it FAILS at some
    # rung slower (lower mV/us) than a rung it PASSES -- i.e. its verdict is
    # not a single step from PASS to FAIL as slew increases. Same predicate
    # analyze_boundary.py flags, reported here with the full sequence rather
    # than as a boolean on a bracket.
    fail_corners, nm_corners = [], []
    for cid in corner_ids:
        passes = [r.slew_mvus for r in rungs if r.status[cid]]
        fails = [r.slew_mvus for r in rungs if not r.status[cid]]
        if fails:
            fail_corners.append(cid)
            if passes and any(f < max(passes) for f in fails):
                nm_corners.append(cid)

    # Band extent, over the corners that are non-monotonic: from the lowest
    # slew at which any of them fails, to the highest slew at which any of
    # them still passes. Above that the failure is unbroken in the tested
    # ladder; below it, every tested rung passes at every corner.
    nm_fail_slews = [
        r.slew_mvus for r in rungs for c in nm_corners if not r.status[c]
    ]
    nm_pass_slews = [
        r.slew_mvus for r in rungs for c in nm_corners if r.status[c]
    ]
    band_lo = min(nm_fail_slews) if nm_fail_slews else None
    band_hi = (
        max(s for s in nm_pass_slews if band_lo is not None and s > band_lo)
        if nm_pass_slews and band_lo is not None
        and any(s > band_lo for s in nm_pass_slews)
        else None
    )

    L: list[str] = []
    L.append(f"# Record {out_id} (derived)")
    L.append("")
    L.append(f"- **Record ID**: {out_id}")
    L.append(
        "- **Claim**: `spec/target-spec.md#por-brownout` clause (c) -- the "
        "SHAPE of the non-monotonic PASS/FAIL band above the ratified "
        "`dVDD/dt|fall,max`, and which of two distinct failure modes each "
        "FAIL in it is (issue #74, following the finding recorded in "
        "`20260802-120940-3c3e728-boundary.md`). **This record does not "
        "re-derive or move the ratified 3.40 mV/us bound**; every rung it "
        "reads is at or above it."
    )
    L.append(
        "- **Derived from** (no new simulation; recombines each source "
        "record's own `pass/fail` column -- see `analyze_transition_band.py`):"
    )
    for r in rungs:
        L.append(
            f"  - `{r.record_id}` -- rung `{r.label}`, {r.slew_mvus:.6g} mV/us "
            f"-- {sum(r.status.values())}/81 PASS"
        )
    L.append("")
    L.append(
        "- **Netlist provenance**: derived -- none of its own; each source "
        "record above carries the netlist snapshot the rung actually ran "
        "against."
    )
    L.append(
        "- **Corner matrix run**: none of its own. Every source record is a "
        "full 81-point PVT grid (9 process corners x -40/27/125 degC x "
        "2.97/3.30/3.63 V); this record reduces them."
    )
    L.append("- **Statistical convention**: N/A (deterministic corner rungs)")
    L.append("")

    L.append("## Ladder map -- every tested rung, not a bracket")
    L.append("")
    L.append(
        "One character per rung, in increasing slew order; `P` = PASS, "
        "`F` = FAIL. The ladder (mV/us), left to right:"
    )
    L.append("")
    L.append("```")
    for i, r in enumerate(rungs):
        L.append(f"{i:>3}  {r.slew_mvus:>8.4g}   {r.label}")
    L.append("```")
    L.append("")
    L.append(
        f"{len(corner_ids) - len(fail_corners)} of the {len(corner_ids)} "
        f"corners PASS at every tested rung and are omitted; the "
        f"{len(fail_corners)} that fail somewhere are listed, "
        f"non-monotonic ones first."
    )
    L.append("")
    L.append("| corner-id | ladder map | non-monotonic? |")
    L.append("|---|---|---|")
    ordered = sorted(
        fail_corners, key=lambda c: (c not in nm_corners, c)
    )
    for cid in ordered:
        smap = "".join("P" if r.status[cid] else "F" for r in rungs)
        L.append(
            f"| `{cid}` | `{smap}` | {'**YES**' if cid in nm_corners else 'no'} |"
        )
    L.append("")
    if nm_corners:
        L.append(
            "**Band extent.** The non-monotonic corners are "
            + ", ".join(f"`{c}`" for c in nm_corners)
            + f". The lowest tested slew at which any of them fails is "
            f"**{band_lo:.6g} mV/us**"
            + (
                f", and the highest tested slew at which any of them still "
                f"passes is **{band_hi:.6g} mV/us** -- so the band in which "
                f"the verdict is not a function of slew alone spans at least "
                f"{band_lo:.6g}...{band_hi:.6g} mV/us on the tested ladder."
                if band_hi is not None
                else ", and no tested rung above it passes at any of them."
            )
        )
    else:
        L.append(
            "**No corner is non-monotonic in the tested ladder.** Every "
            "corner's verdicts are a single PASS->FAIL step as slew rises."
        )
    L.append("")

    if ctl is None:
        L.append(
            "> `control/results.json` is absent, so the mechanism section "
            "below could not be generated. Run "
            "`python3 sim/por-brownout-slew/control/run_band_mechanism.py` "
            "and re-run this script."
        )
        L.append("")
    else:
        L.extend(mechanism_section(ctl))
        L.extend(interpretation_section(ctl))

    L.append("---")
    L.append("")
    L.append(
        "Written by `sim/por-brownout-slew/analyze_transition_band.py`. Per "
        "`sim/README.md`'s derived-record convention: makes no new "
        "measurement, cites its sources, and does not supersede any of them "
        "-- in particular it does not supersede "
        "`20260802-120940-3c3e728-boundary.md`, whose ratified-bound "
        "conclusion it leaves standing."
    )
    L.append("")

    out_path.write_text("\n".join(L))
    print(f"wrote {out_path}")
    print(f"rungs read: {len(rungs)}")
    print(f"non-monotonic corners: {', '.join(nm_corners) or '(none)'}")
    if band_lo is not None:
        print(f"band: {band_lo:.6g} .. {band_hi if band_hi else float('nan'):.6g} mV/us")
    return 0


def classify(rst_min, bound, t_praw, t_pgdg, close_us) -> str:
    """Which of the three things a FAIL verdict can mean.

    The grid records one FAIL for all of them; they are different events and
    implicate different cells, so the record says which.
    """
    if rst_min is None:
        return "—"
    if rst_min <= bound:
        return "PASS"
    if t_praw is None:
        return "**FAIL — no decision**"
    if t_pgdg is None or t_pgdg > close_us:
        return "**FAIL — deglitch unfinished**"
    return "**FAIL — output too late**"


def mechanism_section(ctl: dict) -> list[str]:
    """The WHICH-FAILURE-MODE tables, read from control/results.json."""
    t_dip_s = ctl["t_dip_s"]
    bound = ctl["resetn_ratio_bound"]
    supplies = ctl["supplies_v"]
    slews = ctl["slews_mvus"]
    variants = ctl["variants"]

    def v(name):
        return variants.get(name)

    def name_of(vdd, slew, part="a"):
        return f"{part}-{slew:g}mvus-{vdd:.2f}v"

    L: list[str] = []
    L.append("## Which failure mode is each FAIL?")
    L.append("")
    L.append(
        "Source: `control/results.json` / `control/results.md`, generated by "
        "`control/run_band_mechanism.py` at "
        f"`{ctl['corner']}` / {ctl['temp_c']:g} degC / "
        + ", ".join(f"{s:g} V" for s in supplies)
        + " on the same deck the rungs ran. A control is not corner evidence "
        "and substantiates no spec row (`sim/README.md`) -- the verdicts "
        "themselves come from the 81-point records above; the control only "
        "says what produced them."
    )
    L.append("")
    L.append(
        "The grid's one FAIL verdict (`resetn_ratio_min_in_dip` > "
        f"{bound:g}) covers two physically different events:"
    )
    L.append("")
    L.append(
        "- **NO DECISION** -- `POR_RAW` never asserts during the dip at all. "
        "This is DR-011's starved loop: `BIAS_OK` reads a false valid while "
        "the bank that biases it is driven off, so no threshold decision is "
        "ever taken."
    )
    L.append(
        "- **LATE DECISION** -- `POR_RAW` does assert, well inside the dip, "
        "and the output chain -- starved by the same collapse -- does not "
        "finish propagating it before the dip window closes. `RESETn` then "
        "re-asserts on the recovery edge instead, which is the behaviour "
        "DR-011 already describes for out-of-envelope dips."
    )
    L.append("")
    L.append(
        "All times below are microseconds after the dip starts. *window "
        "closes* is `edge + 50 us dwell`, the end of the window "
        "`testbench/tb.json` measures over; `deglitch` is the interval from "
        "`POR_RAW` asserting to `PGDG` (the deglitched power-good) falling, "
        "i.e. `por_output_chain`'s dwell as actually realized at whatever "
        "bias current survived the collapse."
    )
    L.append("")
    for vdd in supplies:
        L.append(f"### {ctl['corner']} / {ctl['temp_c']:g} degC / {vdd:g} V")
        L.append("")
        L.append(
            "| slew (mV/us) | window closes | `POR_RAW` asserts | rail there "
            "| `PGDG` falls | deglitch | `RESETn` valid-low | margin | "
            "mode |"
        )
        L.append("|---|---|---|---|---|---|---|---|---|")
        for slew in slews:
            d = v(name_of(vdd, slew))
            if d is None:
                continue
            m = d["measurements"]
            close = d["window_close_us"]
            t_praw = us_after_dip(m, "t_praw", t_dip_s)
            t_pgdg = us_after_dip(m, "t_pgdg", t_dip_s)
            t_rst = us_after_dip(m, "t_rst", t_dip_s)
            rst_min = m.get("rst_r_min")
            vdd_praw = m.get("vdd_at_praw")
            mode = classify(rst_min, bound, t_praw, t_pgdg, close)
            L.append(
                f"| {slew:g} | {close:.1f} | "
                + (f"{t_praw:.1f}" if t_praw is not None else "**never**")
                + " | "
                + (f"{vdd_praw:.3f} V" if vdd_praw is not None else "—")
                + " | "
                + (f"{t_pgdg:.1f}" if t_pgdg is not None else "**never**")
                + " | "
                + (
                    f"{t_pgdg - t_praw:.1f}"
                    if (t_praw is not None and t_pgdg is not None)
                    else "—"
                )
                + " | "
                + (f"{t_rst:.1f}" if t_rst is not None else "**never**")
                + " | "
                + (f"{close - t_rst:+.1f}" if t_rst is not None else "—")
                + f" | {mode} |"
            )
        L.append("")

    L.append("### Is it the solver?")
    L.append("")
    L.append(
        f"The same decks re-run with a maximum timestep of "
        f"{ctl['fine_tmax_s']*1e6:g} us instead of the grid's own "
        f"`tran {ctl['tstep_s']*1e6:g}u` with no bound -- "
        f"{ctl['tstep_s']/ctl['fine_tmax_s']:.0f}x finer. If a knife-edge "
        "verdict were an artefact of where the adaptive timestep grid lands "
        "relative to the 50 us dwell, tightening the bound would move it."
    )
    L.append("")
    L.append(
        "| slew (mV/us) | supply | `PGDG` falls, coarse | fine | "
        "min `RESETn`/VDD, coarse | fine | verdict, coarse | fine |"
    )
    L.append("|---|---|---|---|---|---|---|---|")
    for slew in ctl["resolution_slews_mvus"]:
        for vdd in supplies:
            a, b = v(name_of(vdd, slew, "a")), v(name_of(vdd, slew, "b"))
            if a is None or b is None:
                continue
            ta = us_after_dip(a["measurements"], "t_pgdg", t_dip_s)
            tb = us_after_dip(b["measurements"], "t_pgdg", t_dip_s)
            ra = a["measurements"].get("rst_r_min")
            rb = b["measurements"].get("rst_r_min")

            def verd(x):
                return "—" if x is None else ("PASS" if x <= bound else "**FAIL**")

            L.append(
                f"| {slew:g} | {vdd:g} V | "
                + (f"{ta:.1f}" if ta is not None else "**never**")
                + " | "
                + (f"{tb:.1f}" if tb is not None else "**never**")
                + " | "
                + (f"{ra:.4f}" if ra is not None else "—")
                + " | "
                + (f"{rb:.4f}" if rb is not None else "—")
                + f" | {verd(ra)} | {verd(rb)} |"
            )
    L.append("")
    return L


def interpretation_section(ctl: dict) -> list[str]:
    """Confirm-or-refute DR-011's phase-relationship hypothesis against the
    mechanism data above, per issue #74's acceptance criterion 2. Every
    number quoted is read from ``ctl`` (i.e. from the tables already emitted
    by ``mechanism_section``), not asserted independently.
    """
    supplies = ctl["supplies_v"]
    slews = ctl["slews_mvus"]
    variants = ctl["variants"]

    def v(vdd, slew):
        return variants.get(f"a-{slew:g}mvus-{vdd:.2f}v")

    L: list[str] = []
    L.append("## Interpretation -- is DR-011's phase-relationship hypothesis confirmed?")
    L.append("")
    L.append(
        "`20260802-120940-3c3e728-boundary.md` offered a hypothesis, not a "
        "measurement: that the non-monotonicity reflects \"the phase "
        "relationship between the collapsing loop and the measurement "
        "window\" shifting near DR-011's own critical timing. The tables "
        "above let that be checked rather than merely repeated."
    )
    L.append("")

    # Near-tangency: the peak deglitch ramp reached, and the V_sg overdrive
    # remaining, at each tested slew -- read straight out of the control's
    # own C/D measurements (ndg_r_max, vsg_min), not recomputed.
    L.append(
        "**The race is between two collapsing timers, not one.** Every FAIL "
        "in the table above is `RESETn` losing a race against *window "
        "closes*, and the deglitch ramp's own peak height (`NDG`/VDD, 0 = "
        "did not move, ~0.5-0.7 = the level the PASS rows above reliably "
        "cross) shows how close a near-boundary FAIL comes before the "
        "window shuts, rather than the ramp simply failing to start:"
    )
    L.append("")
    L.append(
        "| slew (mV/us) | peak NDG/VDD, 2.97 V | 3.3 V | 3.63 V | min V_sg "
        "in dip, 2.97 V | 3.3 V | 3.63 V |"
    )
    L.append("|---|---|---|---|---|---|---|")
    for slew in slews:
        cells = []
        vsg_cells = []
        for vdd in supplies:
            d = v(vdd, slew)
            m = d["measurements"] if d else {}
            ndg = m.get("ndg_r_max")
            vsg = m.get("vsg_min")
            cells.append(f"{ndg:.3f}" if ndg is not None else "--")
            vsg_cells.append(f"{vsg*1e3:+.1f} mV" if vsg is not None else "--")
        L.append(
            f"| {slew:g} | " + " | ".join(cells) + " | " + " | ".join(vsg_cells) + " |"
        )
    L.append("")
    L.append(
        "Two things follow from this table together with the event-timeline "
        "one above:"
    )
    L.append("")
    L.append(
        "1. **The FAILs in the non-monotonic band are near-tangencies, not "
        "dead circuits.** The underlying state variable -- peak `NDG`/VDD, "
        "how high the deglitch ramp actually got -- declines *continuously* "
        "across the PASS-to-FAIL step (`ss`/3.3 V: 0.664 at 3.42 mV/us, "
        "0.657 at 3.44, then 0.541 the instant it FAILs at 3.46), even "
        "though the verdict itself flips discretely, because a ramp that "
        "does not quite reach the trip point before the window closes "
        "produces the same binary FAIL as one that never moved at all. That "
        "is the near-tangency signature: a continuously-varying margin "
        "behind a discrete PASS/FAIL column, which is exactly the shape "
        "that makes a bisection-style search miscount monotonicity. This is "
        "the same shape DR-011's hypothesis predicted, now measured rather "
        "than inferred."
    )
    L.append(
        "2. **`min V_sg in dip`'s sign is not itself the discriminator.** "
        "At 2.97 V it stays positive up to 3.613 mV/us and only inverts at "
        "3.7 mV/us, well *after* that supply's own deglitch race is already "
        "lost (3.4795 mV/us, per the event-timeline table) -- a few mV of "
        "shaved overdrive, not a full shutoff, is already enough to stretch "
        "the deglitch dwell past the shrinking window. At 3.3 V and 3.63 V "
        "it is negative at *every* tested slew, including the healthiest "
        "PASS rows (3.351 mV/us: -84.0 mV / -113.5 mV) -- so a brief "
        "overdrive inversion during the dip is normal at those supplies and "
        "does not by itself predict the verdict either way. What tracks the "
        "verdict is the deglitch race margin in the event-timeline table, "
        "not `V_sg`'s sign at any single instant."
    )
    L.append("")

    L.append(
        "**Why the crossing point differs by supply.** "
        "`design/por_output_chain.md` documents the deglitch dwell as "
        "1.86-4.58 us at nominal `IBIAS` and 3.61-8.88 us at half, and "
        "`spec/decision-records/DR-011-brownout-falling-slew-limit.md`'s own "
        "control C measures `por_output_chain` reaching valid-low in "
        "3.70-7.30 us **down to zero `IBIAS`** -- but that control drives "
        "`POR_RAW` directly at a rail already settled at 1.0 V, decoupled "
        "from `bias_core`'s own collapse. The event-timeline table above "
        "shows every `deglitch` interval it could measure in this band "
        "running from several hundred microseconds up to 1048.1 us "
        "(`ss`/2.97 V at 3.4795 mV/us) -- one to two orders of magnitude "
        "past both documented ceilings where it resolves at all -- because "
        "in this regime the edge has not finished: at "
        "the near-boundary slews, `POR_RAW` asserts only 70-120 us into an "
        "edge that does not close its window for another 500-800 us, so the "
        "deglitch tail draws whatever current survives a collapse that is "
        "still in progress, not a settled one. That collapse trajectory -- "
        "how much overdrive is left at each instant, not merely at the "
        "moment `POR_RAW` trips -- is itself a function of the starting "
        "supply (a higher `vdd_val` buys a longer absolute edge duration for "
        "the same mV/us, and a different pre-dip operating point), which is "
        "the concrete reason the race's winner is not a function of slew "
        "rate alone: `ss_-40c_3.30v` and `ss_-40c_3.63v` cross this "
        "near-tangency at slightly different slews (see the ladder map "
        "above), while `ss_-40c_2.97v` -- whose absolute edge is shortest, "
        "leaving the least room in the race regardless -- fails first and "
        "does not recover in the tested ladder."
    )
    L.append("")
    L.append(
        "**Assessment: confirmed, and refined into a concrete mechanism.** "
        "The finding is consistent with DR-011's own framing -- a "
        "nonlinear relaxation dynamic near its own critical timing -- and "
        "the \"phase relationship\" language is now a specific, measured "
        "quantity: the margin between the deglitch dwell realized under "
        "in-progress bias collapse and the shrinking dip window, which the "
        "near-tangency data above shows crossing zero at slightly different "
        "slews for the three supply points rather than in lockstep. It is "
        "**not** a claim that `por_output_chain` is defective -- DR-011's "
        "control C and this record's own solver check (above) both stand -- "
        "only that the STATIC, decoupled-current condition those controls "
        "tested does not cover the DYNAMIC, still-falling-edge condition "
        "the non-monotonic band lives in. Neither this record nor its "
        "underlying data revisits or narrows "
        "`spec/target-spec.md#por-brownout` clause (c)'s ratified 3.40 "
        "mV/us bound: every PASS margin at or below 3.40 mV/us in the "
        "event-timeline table above (108.7-231.1 us, at 3.351 and 3.40 "
        "mV/us, the only two tested points at or below the ratified bound) "
        "sits well clear of this near-tangency band, which only opens at "
        "3.46 mV/us and above."
    )
    L.append("")
    return L


if __name__ == "__main__":
    raise SystemExit(main())
