"""Deck composition and ngspice execution for one PVT point."""

from __future__ import annotations

import hashlib
import re
import shutil
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path

from .corners import Corner, PvtPoint
from .pdk import Pdk
from .testbench import Testbench

NGSPICE = "ngspice"
DEFAULT_TIMEOUT_S = 300

# `print` output for a length-1 vector: "m_vout = 6.9043645202e-01"
_MEAS_RE = re.compile(r"^\s*m_(\w+)\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)\s*$")
_ERROR_RE = re.compile(r"^\s*(?:Error|ERROR|Fatal|fatal error|doAnalyses:)", re.MULTILINE)

# `print <expr>` output for a bare (non `m_`-prefixed) probe, e.g. an `.op`
# node voltage or current: "@m.xdut.xmoka.m0[id] = 6.9043645202e-01". Shared
# home for the per-experiment `parse_prints()` copies that used to be
# redefined in sim/bias-core-startup/control/run_gmin_control.py and
# sim/temp-accuracy-mc/control/run_mismatch_switch.py.
_PRINT_RE = re.compile(r"^\s*(\S+)\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)\s*$")

# ngspice `.measure` output for the bare-name-with-optional-`at=` convention:
# `name = value` for find/when, `name = value at= t` for min/max. A
# *different* naming convention than `_MEAS_RE` above (which requires the
# `m_` prefix `let`-aliased in compose_deck()) -- this one matches `.measure`
# statements written directly against `name`, as used by control scripts
# that don't route through `compose_deck()`. Shared home for the per-
# experiment `_MEAS_RE` + measurement-parsing loop copies that used to be
# redefined in sim/por-brownout/control/run_dip_rootcause.py and
# sim/por-brownout-slew/control/run_band_mechanism.py.
_BARE_MEAS_RE = re.compile(r"^\s*([a-z_0-9]+)\s*=\s*([-+0-9.eE]+)\s*(?:at=.*)?$")


class NgspiceMissing(RuntimeError):
    pass


def ngspice_version() -> str:
    exe = shutil.which(NGSPICE)
    if not exe:
        raise NgspiceMissing(
            "ngspice not found on PATH.\n"
            "  macOS:  brew install ngspice\n"
            "  Debian: apt-get install ngspice"
        )
    out = subprocess.run(
        [exe, "--version"], capture_output=True, text=True, check=False
    ).stdout
    for line in out.splitlines():
        if "ngspice-" in line:
            return line.strip().lstrip("* ").strip()
    return out.strip().splitlines()[0] if out.strip() else "unknown"


def deck_preamble(pdk: Pdk, corner: Corner, temp_c: float, options: list[str]) -> list[str]:
    """The pdk-include + corner ``.lib`` + ``.temp`` + ``.options`` ngspice
    deck fragment shared by every call site that composes a corner-swept
    deck: the design's own ``compose_deck()`` below, plus the three
    ``control/`` root-cause scripts that build their own decks against the
    same corner/temp/options axes (``sim/por-glitch/control/run_glitch_probe.py``,
    ``sim/por-glitch/control/run_depth_sweep.py``,
    ``sim/por-ramp-rate/control/run_chatter_probe.py``). Line shapes match
    exactly what those four call sites used to derive independently, so
    switching a caller over to this helper does not change any generated
    deck's text.
    """
    lines: list[str] = [f'.include "{pdk.design_include}"']
    lines += [f'.lib "{pdk.model_lib}" {section}' for section in corner.sections]
    lines += ["", f".temp {temp_c!r}"]
    lines += [f".options {option}" for option in options]
    return lines


def compose_deck(tb: Testbench, pdk: Pdk, point: PvtPoint) -> str:
    """Build the complete, self-contained ngspice deck for one PVT point."""
    lines: list[str] = [
        f"* {tb.name} @ {point.corner_id} -- GENERATED by sim/harness, do not edit",
        f"* corner={point.corner.name} ({point.corner.description})",
        f"* temp={point.temp_c} C  vdd={point.vdd} V  pdk={pdk.variant}@{pdk.version}",
        "",
        "* ---- PVT parameters -------------------------------------------------",
        f".param vdd_nom={tb.nominal_supply_v!r}",
        f".param vdd_val={point.vdd!r}",
        f".param temp_c={point.temp_c!r}",
    ]
    for key, value in tb.params.items():
        lines.append(f".param {key}={value}")

    lines += [
        "",
        "* ---- gf180mcu models ------------------------------------------------",
    ]
    lines += deck_preamble(pdk, point.corner, point.temp_c, tb.options)

    lines += [
        "",
        "* ---- testbench ------------------------------------------------------",
        f'.include "{tb.netlist}"',
        "",
        "* ---- measurement ----------------------------------------------------",
        ".control",
        "set numdgt=10",
        "set noaskquit",
    ]
    lines += [f"  {analysis}" for analysis in tb.analyses]
    for name, expr in tb.measure.items():
        lines.append(f"  let m_{name} = {expr}")
    for name in tb.measure:
        lines.append(f"  print m_{name}")
    lines += [".endc", ".end", ""]
    return "\n".join(lines)


@dataclass
class PointResult:
    point: PvtPoint
    status: str                                   # "ok" | "failed" | "error"
    measurements: dict[str, float] = field(default_factory=dict)
    missing: list[str] = field(default_factory=list)
    seconds: float = 0.0
    deck: str = ""
    log: str = ""
    message: str = ""

    def as_dict(self) -> dict:
        record = self.point.as_dict()
        record.update(
            {
                "status": self.status,
                "measurements": self.measurements,
                "seconds": round(self.seconds, 3),
                "deck": self.deck,
                "log": self.log,
            }
        )
        if self.missing:
            record["missing_measurements"] = self.missing
        if self.message:
            record["message"] = self.message
        return record


def parse_measurements(text: str) -> dict[str, float]:
    found: dict[str, float] = {}
    for line in text.splitlines():
        match = _MEAS_RE.match(line)
        if match:
            try:
                found[match.group(1)] = float(match.group(2))
            except ValueError:  # pragma: no cover - regex already constrains this
                continue
    return found


def parse_prints(text: str) -> dict[str, float]:
    """Parse bare ``print <expr>`` output: ``<expr> = <value>``, one line per
    probe, as emitted by an ``.op`` control block (as opposed to
    ``parse_measurements`` above, which requires the ``m_`` prefix
    ``compose_deck()`` writes).

    Shared home for the per-experiment ``parse_prints()`` copies that used to
    be redefined in sim/bias-core-startup/control/run_gmin_control.py and
    sim/temp-accuracy-mc/control/run_mismatch_switch.py.
    """
    found: dict[str, float] = {}
    for line in text.splitlines():
        match = _PRINT_RE.match(line)
        if match:
            try:
                found[match.group(1)] = float(match.group(2))
            except ValueError:  # pragma: no cover - regex already constrains this
                continue
    return found


def parse_bare_measurements(text: str) -> dict[str, float]:
    """Parse ngspice ``.measure`` output under the bare-name convention
    (``_BARE_MEAS_RE`` above) -- as opposed to ``parse_measurements``, which
    requires the ``m_`` prefix.

    Shared home for the per-experiment ``_MEAS_RE``/``parse_measurements()``
    copies that used to be redefined in
    sim/por-brownout/control/run_dip_rootcause.py (inlined in ``run_deck()``)
    and sim/por-brownout-slew/control/run_band_mechanism.py.
    """
    found: dict[str, float] = {}
    for line in text.splitlines():
        match = _BARE_MEAS_RE.match(line)
        if match:
            try:
                found[match.group(1)] = float(match.group(2))
            except ValueError:
                continue
    return found


def find_crossings(
    rows: list[tuple[float, ...]],
    col: int,
    thresh: float,
    t0: float | None = None,
) -> list[tuple[float, str]]:
    """Every threshold crossing of ``rows[:, col]``, optionally restricted to
    rows at or after ``t0``.

    Shared home for the per-experiment ``find_crossings()`` copies that used
    to be redefined in sim/por-glitch/control/run_glitch_probe.py (which
    passed a ``t0`` skip-until-timestamp) and
    sim/por-ramp-rate/control/run_chatter_probe.py (which scanned every row).
    ``t0=None`` (the default) reproduces the latter's no-skip behavior.
    """
    crossings: list[tuple[float, str]] = []
    prev = None
    for row in rows:
        if t0 is not None and row[0] < t0:
            prev = row
            continue
        if prev is None:
            prev = row
            continue
        a, b = prev[col], row[col]
        if (a - thresh) * (b - thresh) < 0:
            crossings.append((row[0], "rise" if b > a else "fall"))
        prev = row
    return crossings


def parse_wrdata_trace(text: str, n_probes: int) -> list[tuple[float, ...]]:
    """Parse ngspice ``wrdata`` output: ``t v0 t v1 t v2 ...``, one repeated
    ``(t, value)`` pair per probe.

    Shared home for the per-experiment ``parse_trace(text)`` copies that used
    to be redefined in every control script tracing internal nodes with
    ``wrdata`` (as opposed to ``print``, which ``parse_measurements`` above
    covers). ``n_probes`` is the caller's probe count -- each row is expected
    to have exactly ``2 * n_probes`` whitespace-separated fields; malformed or
    short rows are skipped rather than raising.
    """
    rows: list[tuple[float, ...]] = []
    for line in text.splitlines():
        parts = line.split()
        if len(parts) != 2 * n_probes:
            continue
        try:
            vals = [float(x) for x in parts]
        except ValueError:
            continue
        t = vals[0]
        row = (t,) + tuple(vals[1 + 2 * i] for i in range(n_probes))
        rows.append(row)
    return rows


def sha256_file(path: Path) -> str:
    """The hex sha256 digest of ``path``'s contents.

    Shared home for the per-experiment ``sha256(path)`` copies that used to
    be redefined in every control/analysis script; see
    ``layout/lvs_reference.sha256_bytes`` for the layout-side equivalent.
    """
    return hashlib.sha256(path.read_bytes()).hexdigest()


def git_describe(repo_root: Path, generated: tuple[str, ...]) -> str:
    """HEAD, plus whether anything OTHER than ``generated`` paths is dirty.

    Regenerating a control script in place necessarily dirties its own
    output paths (a ``results.md``, a ``decks/`` directory, raw ``logs/``,
    and similar), so counting those as "dirty" would report every re-run as
    taken against a dirty tree -- the same trap ``sim/harness/report.py``
    avoids by sampling git before the run. What matters for provenance is
    the state of the *inputs*: everything in the working tree except this
    script's own declared outputs.

    ``generated`` is a tuple of repo-root-relative path strings (as
    ``str(path.relative_to(repo_root))``) that ``git status --porcelain``
    entries are allowed to start with without counting as "dirty".
    """

    def _git(*args: str, strip: bool = True) -> str:
        out = subprocess.run(
            ["git", *args], cwd=repo_root, capture_output=True, text=True, check=False
        ).stdout
        # `git status --porcelain` encodes the status in the FIRST TWO
        # COLUMNS, and an unstaged modification leaves column 1 blank -- so
        # stripping here would shift the first line's path left by one
        # character and make the "is this one of my own outputs" filter
        # below miss it, reporting a clean tree as dirty. Only strip when
        # the caller wants a bare value.
        return out.strip() if strip else out

    other = [
        line
        for line in _git("status", "--porcelain", strip=False).splitlines()
        if not line[3:].strip('"').startswith(generated)
    ]
    state = "dirty" if other else "clean apart from this experiment's own outputs"
    return f"{_git('rev-parse', 'HEAD')} ({state})"


def run_point(
    tb: Testbench,
    pdk: Pdk,
    point: PvtPoint,
    workdir: Path,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    log_dir: Path | None = None,
) -> PointResult:
    """Simulate one PVT point. Never raises for simulation failure.

    ``workdir`` holds the generated deck (scratch, disposable). ``log_dir``
    -- when given -- is where the raw ngspice output lands as
    ``<corner-id>.log``; that is the ``sim/<slug>/corners/<record-id>/``
    directory from ``sim/README.md``. It defaults to ``workdir`` so a
    throwaway run does not touch the evidence tree.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    log_dir = workdir if log_dir is None else log_dir
    log_dir.mkdir(parents=True, exist_ok=True)
    deck_path = workdir / f"{point.corner_id}.spice"
    log_path = log_dir / f"{point.corner_id}.log"
    deck_path.write_text(compose_deck(tb, pdk, point))

    started = time.monotonic()
    try:
        proc = subprocess.run(
            [NGSPICE, "-b", str(deck_path)],
            capture_output=True,
            text=True,
            timeout=timeout_s,
            cwd=workdir,
            check=False,
        )
        output = proc.stdout + "\n" + proc.stderr
        returncode = proc.returncode
    except FileNotFoundError as exc:
        raise NgspiceMissing(str(exc)) from exc
    except subprocess.TimeoutExpired:
        elapsed = time.monotonic() - started
        log_path.write_text(f"TIMEOUT after {timeout_s}s\n")
        return PointResult(
            point=point,
            status="error",
            seconds=elapsed,
            deck=deck_path.name,
            log=log_path.name,
            message=f"ngspice timed out after {timeout_s}s",
        )
    elapsed = time.monotonic() - started
    log_path.write_text(output)

    measurements = parse_measurements(output)
    missing = [name for name in tb.measure if name not in measurements]

    if missing:
        errors = "; ".join(_ERROR_RE.findall(output)[:3])
        first_error = next(
            (line.strip() for line in output.splitlines() if _ERROR_RE.match(line)), ""
        )
        return PointResult(
            point=point,
            status="failed",
            measurements=measurements,
            missing=missing,
            seconds=elapsed,
            deck=deck_path.name,
            log=log_path.name,
            message=first_error or errors or f"ngspice exit {returncode}, no measurements parsed",
        )

    return PointResult(
        point=point,
        status="ok",
        measurements=measurements,
        seconds=elapsed,
        deck=deck_path.name,
        log=log_path.name,
    )


def run_grid(
    tb: Testbench,
    pdk: Pdk,
    points: list[PvtPoint],
    workdir: Path,
    jobs: int = 1,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    on_result=None,
    log_dir: Path | None = None,
) -> list[PointResult]:
    """Run every PVT point; results come back in grid order regardless of jobs."""
    results: list[PointResult | None] = [None] * len(points)

    def _one(index_point):
        index, point = index_point
        result = run_point(tb, pdk, point, workdir, timeout_s=timeout_s, log_dir=log_dir)
        results[index] = result
        if on_result is not None:
            on_result(result)
        return result

    if jobs <= 1:
        for item in enumerate(points):
            _one(item)
    else:
        with ThreadPoolExecutor(max_workers=jobs) as pool:
            list(pool.map(_one, enumerate(points)))

    return [r for r in results if r is not None]
